### ISSUE TITLE
New API documentation ?

### ISSUE THREAD

**Issue by 80avin** [thellmund/Android-Week-View#1]
This library has changed API (in 3.0) but the documentation of new API isn't anywhere.
From what I found, this seems to be most actively maintained. As such, documentation of any level (thorough or simple list of API methods) would be very helpful.

**Comment by thellmund** [comment]
I’m providing an overview of all attributes and listeners in the readme, but I can see how that’s not thorough enough. I hope to find some time this weekend to provide a more detailed documentation.

**Comment by thellmund** [comment]
@80avin I’ve just pushed version 3.1 and added a more detailed documentation in the [wiki](https://github.com/thellmund/Android-Week-View/wiki). Next, I’ll work on improving the JavaDoc. Let me know if there’s anything missing.

**Comment by 80avin** [comment]
@thellmund Checked that !
I'm regular from few weeks on this project, and will be assisting in wherever the need comes.

**Comment by thellmund** [comment]
Sounds good. I will close this issue for now, but feel free to open new issues when anything comes up.
