### ISSUE TITLE
Event rect is not drawn when event that lasts the whole day is added.

### ISSUE THREAD

**Issue by Menthuss** [thellmund/Android-Week-View#10]
When adding an event that starts at 2018-11-21T:00 and ends at 2018-11-21T00:00, the library does not draw a proper event rect and thus, the event will not be visible. I fixed this issue in the [Quivr fork](https://github.com/Quivr/Android-Week-View/pull/57) but it was never merged as it is no longer maintained.

**Comment by thellmund** [comment]
Feel free to open a PR with the same changes on my fork – I’m happy to take a look 😊

**Comment by Menthuss** [comment]
I've fixed the issue in a PR ([here](https://github.com/thellmund/Android-Week-View/pull/11)) however, I discovered a new bug in the process.

**Comment by thellmund** [comment]
The PR is merged. Will take a look at the other issue next.
