### ISSUE TITLE
Vertical gap

### ISSUE THREAD

**Issue by christian160984** [thellmund/Android-Week-View#100]
![Screenshot_20190801-105912_Reserva de salas](https://user-images.githubusercontent.com/7393899/62280197-babce800-b44b-11e9-9f86-5b73b5ec5262.jpg)

I have used eventMarginVertical = 0dp but the white line between events not disappear. It is possible make this?

Thanks

**Comment by thellmund** [comment]
I can’t reproduce this behavior. Here’s what I get in the sample app if I set `eventMarginVertical` to `0dp` and have two consecutive events.

![Screenshot_1564651173](https://user-images.githubusercontent.com/11819826/62281590-518aa400-b44e-11e9-9b6e-c25e2c6c830b.png)

Please provide me with a small sample app that demonstrates the incorrect behavior, just like it was done [here](https://github.com/thellmund/Android-Week-View/issues/54#issuecomment-487428487).

**Comment by christian160984** [comment]
I have managed to know the issue. If the event is less than 30 minutes, `eventMarginVertical` not works.

**Comment by thellmund** [comment]
This is not the cause. The two events below are both 15 minutes long and the vertical margin is correct.

![Screenshot_1564655090](https://user-images.githubusercontent.com/11819826/62286296-b696c780-b457-11e9-94bd-0def9bf661a5.png)

Again, please **provide a small sample app** that demonstrates the behavior. Otherwise, I will not be able to fix your issue.

**Comment by christian160984** [comment]
I am having other problem. `eventMarginVertical="20dp"` not works and the events with less 30 min has a little margin and the events with 30 min or more not.

<com.alamkanak.weekview.WeekView
                android:id="@+id/weekView"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:horizontalScrollingEnabled="true"
                app:columnGap="20dp"
                app:eventMarginVertical="20dp"
                app:eventCornerRadius="3dp"
                app:eventPadding="4dp"
                app:eventTextSize="10sp"
                app:firstDayOfWeek="monday"
                app:headerRowBottomLineWidth="1dp"
                app:headerRowPadding="10dp"
                app:headerRowTextSize="15sp"
                app:hourHeight="52dp"
                app:nowLineDotRadius="9dp"
                app:nowLineStrokeWidth="1dp"
                app:numberOfVisibleDays="1"
                app:showFirstDayOfWeekFirst="true"
                app:showHeaderRowBottomLine="true"
                app:showNowLine="true"
                app:showNowLineDot="true"
                app:showTimeColumnSeparator="true"
                app:singleDayHorizontalMargin="0dp"
                app:singleLineHeader="false"
                app:timeColumnPadding="20dp"
                app:timeColumnSeparatorStrokeWidth="1dp"
                app:timeColumnTextSize="12sp"
                app:horizontalFlingEnabled="false"/>
