### ISSUE TITLE
notifyDataSetChanged don't work

### ISSUE THREAD

**Issue by MohammadB72** [thellmund/Android-Week-View#101]
**Describe the bug**
notifyDataSetChanged  just work in every day

**To Reproduce**
1. add some events before (get From DataBse)
![Screenshot_20190804-183058](https://user-images.githubusercontent.com/15035925/62424611-3c2fa700-b6e6-11e9-98e4-2dd2c29001c2.png)

**2. Click on the new area to add new event**
![Screenshot_20190804-183106](https://user-images.githubusercontent.com/15035925/62424632-92044f00-b6e6-11e9-9d1c-b9734e873b69.png)

**3. after that click on another area (in my algorithm logic last event that i added it by clicking on the empty area must be deleted an add the new one) but the result is : new event added last event stay yet**
![Screenshot_20190804-183116](https://user-images.githubusercontent.com/15035925/62424664-32f30a00-b6e7-11e9-9be1-299935b02ad4.png)

**4. but after clicking on another empty event at the same day it has been cleared**
![Screenshot_20190804-183122](https://user-images.githubusercontent.com/15035925/62424684-6897f300-b6e7-11e9-9bab-1a53fd546a37.png)

**Comment by thellmund** [comment]
Thanks for reporting, @MohammadB72. I fixed the issue and will release it with version 4.0 in the next few days.
