### ISSUE TITLE
Multiple all-day events are displayed

### ISSUE THREAD

**Issue by tdc-w** [thellmund/Android-Week-View#104]
**Describe the bug**
It seems that multiple all-day events are displayed when across the month.
Is there any solution?

**Screenshots**
・across the month

<img src="https://user-images.githubusercontent.com/38201241/63870893-dc32d480-c9f5-11e9-8a7b-c55880fd2ae7.png" width="300">

・not across (expected behavior)

<img src="https://user-images.githubusercontent.com/38201241/63870894-dc32d480-c9f5-11e9-9a3d-9e36150810aa.png" width="300">

**Additional context**
 - Android version: [Android 7.0]
 - WeekView version: [3.4.2]

**Comment by thellmund** [comment]
Can you prepare a small sample app that showcases the issue? I wasn’t able to reproduce it in my sample app.

**Comment by tdc-w** [comment]
Sorry, sample may not be ready immediately.
As logic, when the month of newFirstVisibleDay of scrollListener changes, the data of that month is acquired and displayed.
So, in the case of data that across the month, I think that the data has been duplicated, I think that it is necessary to correct the function of eventMatches.
I will investigate a little more.

**Comment by tdc-w** [comment]
I confirmed the sample of the develop branch.
The sample of the master branch used onMonthChangeListener.
In the future, has it been modified so that events can be displayed without using onMonthChangeListener?

**Comment by thellmund** [comment]
I don’t understand what you mean. Please explain it in a clearer way.

**Comment by tdc-w** [comment]
Sorry for the confusing explanation.

I currently use eventMatches function in AsyncActivity of sample.
https://github.com/thellmund/Android-Week-View/commit/a3bc6013159c2a39bf091f760f5f77c4e488010d#diff-ac1981acaaa8efdf9fba7edc076bf0c8L132

In the previous sample, the processing is a little different.
https://github.com/thellmund/Android-Week-View/blob/master/sample/src/main/java/com/alamkanak/weekview/sample/AsyncActivity.kt#L130

and it will behave as follows.
<img src="https://user-images.githubusercontent.com/38201241/64161225-432e0e80-ce78-11e9-823c-8d25d71a2812.gif" width="300">

So I thought it would be fixed if eventMatches was modified.


But in next version(your develop branch), the process seems to change.
https://github.com/thellmund/Android-Week-View/blob/develop/sample/src/main/java/com/alamkanak/weekview/sample/AsyncActivity.kt#L73

So my problem may be solved in next version.

**Comment by tdc-w** [comment]
I've created a sample so it would be helpful if you could check it.
https://github.com/tdc-w/sample_weekview

**Comment by thellmund** [comment]
Thanks for providing a sample. The issue that causes the wrong behavior is something that I have already fixed on the `develop` branch, but haven’t yet released as a new version. 

When I switched to `com.github.thellmund.Android-Week-View:core:develop-SNAPSHOT` (just for testing; don’t do this!), the issue no longer occurred. 

I will take a few more days to polish the next release. With it, your issue should be fixed for good. I’ll close this issue now. Feel free to re-open if anything comes up again.

**Comment by thellmund** [comment]
Also, you might want to have a look at #87. It describes how the next release will it make easier to use `WeekView` in combination with view models and observers.

**Comment by tdc-w** [comment]
Thanks for the explanation.
I look forward to the next release.
