### ISSUE TITLE
Call WeekView.submit() with two periods leads to crash

### ISSUE THREAD

**Issue by SE7-KN8** [thellmund/Android-Week-View#107]
**Describe the bug**
```java
    java.lang.IllegalStateException: AsyncLoader attempted to cache 2 periods, which should not be possible.
        at com.alamkanak.weekview.AsyncLoader.updateEventsCache(AsyncLoader.kt:76)
        at com.alamkanak.weekview.AsyncLoader.submit(AsyncLoader.kt:61)
        at com.alamkanak.weekview.WeekView.submit(WeekView.kt:1267)
```

**To Reproduce**
Call `WeekView.submit()` with events which are from two different months.

**Additional context**
 - Android version: Android 9.0
 - WeekView version: current develop branch

**Comment by thellmund** [comment]
Thanks for reporting, @SE7-KN8. I refactored the entire code around events loading and caching in 820953067cc6ab244e00f3f72800135bbc339153 – give it a try! 

I’ll go ahead and close this issue for now. Let me know if any issues persist.

**Comment by SE7-KN8** [comment]
Just tested it, everything works as it should be. Thanks for fixing.👍
