### ISSUE TITLE
Possibilty to add formater on the headerRow

### ISSUE THREAD

**Issue by thelittlefireman** [thellmund/Android-Week-View#108]
**Is your feature suggestion related to a problem? Please describe.**
Header row (Day) is always in an english format "Dim 9/31" (Month/Day)

**Describe the solution you'd like**
Could it be possible to add a formater for the header row (Day) ? To change from eng format : "Dim 9/31" (Month/Day)" to french format "Dim 31/09" (Day/Month)"?

**Describe alternatives you've considered**

**Additional context**

**Comment by thellmund** [comment]
You can already do that by providing your own `DateTimeInterpreter` (see [documentation](https://github.com/thellmund/Android-Week-View/wiki/Listeners#date-formatting)).
