### ISSUE TITLE
 No WeekViewLoader or MonthChangeListener provided.

### ISSUE THREAD

**Issue by rajextreme9476** [thellmund/Android-Week-View#112]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Additional context**
 - Android version: [e.g. Android 9.0]
 - WeekView version: [e.g. 3.4.2]

**Comment by thellmund** [comment]
Please provide a description of your issue.

**Comment by rajextreme9476** [comment]
submit() method not found

**Comment by thellmund** [comment]
That doesn’t give me much of a clue about the cause of the issue. Please provide me with a stacktrace and a description of what you did before the issue occurred.

**Comment by thellmund** [comment]
Closed due to inactivity.
