### ISSUE TITLE
Allow to override some features

### ISSUE THREAD

**Issue by Skyost** [thellmund/Android-Week-View#113]
**Is your feature suggestion related to a problem? Please describe.**
In fact, I want to change some little details about drawers.

**Describe the solution you'd like**
I wanna be able to override some fields in the `WeekView` class.

**Describe alternatives you've considered**
Download the whole project sources and change what I want. But that's not the concept of OOP.

**Additional context**
I'm gonna fully describe my problem here. First thanks a lot for maintaining this library, it's really cool.    
What I want is to change the way events are being drawn. For this, I need to override the `SingleEventsDrawer` field in the `WeekView` class. And after that, I need to override the `EventChipDrawer` class. But I can't because everything in this library is private and final. 😞

**Comment by thellmund** [comment]
Glad you like the library. Would you mind sharing how you‘d want to change the drawing behavior? Maybe it’s something I can incorporate into the main library code.

**Comment by Skyost** [comment]
Well I did it in an older version but I think the trick may work in the current version either. So here's the idea :

When displaying small events (or after an unzoom), Android-Week-View completely hides their titles. After some researches, I've changed some little things in the `EvenChip` class.

<img src="https://user-images.githubusercontent.com/3882599/64919485-9c1c7180-d7ab-11e9-8198-7b1465be2241.gif" height="500">
_Using Android Week View v3.4.2_

<img src="https://user-images.githubusercontent.com/3882599/64919490-ab032400-d7ab-11e9-8984-49155f11497e.gif" height="500">
_Using my custom `EventChip` class_

So here's my code if you're interested :

```java
private void calculateTextHeightAndDrawTitle(WeekViewConfigWrapper config, Canvas canvas) {
	final boolean negativeWidth = (rect.right - rect.left - config.getEventPadding() * 2) < 0;
	final boolean negativeHeight = (rect.bottom - rect.top - config.getEventPadding() * 2) < 0;
	if (negativeWidth || negativeHeight) {
		return;
	}

	// Prepare the name of the event.
	int titleLength = -1;
	final SpannableStringBuilder stringBuilder = new SpannableStringBuilder();
	if (event.getTitle() != null) {
		titleLength = event.getTitle().length();
		stringBuilder.append(event.getTitle());
		stringBuilder.setSpan(new StyleSpan(Typeface.BOLD), 0, titleLength, 0);
	}

	// Prepare the location of the event.
	if (event.getLocation() != null) {
		stringBuilder.append(' ');
		stringBuilder.append(event.getLocation());
	}

	final int availableHeight = (int) (rect.bottom - rect.top - config.getEventPadding() * 2);
	final int availableWidth = (int) (rect.right - rect.left - config.getEventPadding() * 2);

	// Get text dimensions.
	final TextPaint textPaint = event.getTextPaint(config);

	textPaint.setColor(event.getTextColorOrDefault(config));

	StaticLayout textLayout = new StaticLayout(stringBuilder,
			textPaint, availableWidth, ALIGN_NORMAL, 1.0f, 0.0f, false);

	final int lineHeight = textLayout.getHeight() / textLayout.getLineCount();

	if (availableHeight >= lineHeight) {
		int availableLineCount = availableHeight / lineHeight;
		int actualLines = textLayout.getLineCount();

		try {
			while(textLayout.getHeight() > availableHeight && availableLineCount > 0) {
				// TODO: Don't truncate
				// Ellipsize text to fit into event rect.

				int start = textLayout.getLineStart(availableLineCount);
				int end = textLayout.getLineEnd(availableLineCount);

				stringBuilder.delete(end, stringBuilder.length());
				end = stringBuilder.length();

				CharSequence lastLine = stringBuilder.subSequence(start, end);
				stringBuilder.delete(start, end);

				if(availableLineCount < actualLines - 1) {
					if(lastLine.toString().replace("\r\n", "").replace("\n", "").trim().isEmpty()) {
						stringBuilder.append("…");
					}
					else {
						final CharSequence ellipsize = TextUtils.ellipsize(lastLine, textPaint, availableWidth, TextUtils.TruncateAt.END);
						stringBuilder.append(ellipsize);
						if(lastLine.equals(ellipsize)) {
							stringBuilder.delete(stringBuilder.length() - 2, stringBuilder.length());
							stringBuilder.append('…');

							if(end >= titleLength && titleLength != -1) {
								stringBuilder.setSpan(new StyleSpan(Typeface.BOLD), 0, Math.min(end, titleLength), 0);
							}
						}
					}
				}

				textLayout = new StaticLayout(stringBuilder,
						textPaint, availableWidth, ALIGN_NORMAL, 1.0f, 0.0f, false);

				// Repeat until text is short enough.
				availableLineCount--;
			}

			// Draw text.
			drawEventTitle(config, textLayout, canvas);
		}
		catch(final Exception ex) {
			ex.printStackTrace();
		}
	}
}
```

**Comment by thellmund** [comment]
I’d recommend waiting for version 4, which I hope to release in the next few days. It includes adaptive text sizes (added here: f29a966675424b8a8d6675be26838629c5ca6fec). Try out the sample app to see it in action.

The other solution would be to fork my repository and replace the implementation of `EventChip` with your own.

**Comment by Skyost** [comment]
> I’d recommend waiting for version 4, which I hope to release in the next few days. It includes adaptive text sizes (added here: f29a966). Try out the sample app to see it in action.

Cool, I'm gonna wait then.

> The other solution would be to fork my repository and replace the implementation of EventChip with your own.

I know that but I find it too bad to not just override some features because they are private and / or final.
