### ISSUE TITLE
Device rotation leads to crash.

### ISSUE THREAD

**Issue by MikibeMiki** [thellmund/Android-Week-View#117]
After device is rotated, application crashes with following error:

`java.lang.IllegalStateException: Required value was null.
        at com.alamkanak.weekview.PagedEventsCache.update(EventsCache.kt:162)
        at com.alamkanak.weekview.PagedEventsCache.update(EventsCache.kt:157)
        at com.alamkanak.weekview.EventsDiffer.submitItems(EventsDiffer.kt:69)
        at com.alamkanak.weekview.EventsDiffer.access$submitItems(EventsDiffer.kt:20)
        at com.alamkanak.weekview.EventsDiffer$submit$1.run(EventsDiffer.kt:41)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)`

**Additional context**
 - Android version:  Android 6.0.1
 - WeekView version: core:4.0.0

**Comment by thellmund** [comment]
Thanks for reporting, @MikibeMiki. Can you provide a link to a repository with a sample app (like [this one](https://github.com/thellmund/Android-Week-View/issues/106#issuecomment-526854433)) that showcases the crash? That will make it a lot easier for me to fix.

**Comment by MikibeMiki** [comment]
Hi, here is example app which leads to crash when device is rotated:

https://github.com/MikibeMiki/WeekViewIssue

Also, if you remove line 27 in MainFragment, during rotation sometimes ConcurentModificationException occurs.

**Comment by thellmund** [comment]
Thanks, I’ll take a look at this tomorrow.

**Comment by thellmund** [comment]
Sorry for the delay. I have not resolved the issue yet, but I have found the reason for why it occurs: The simultaneous use of both `weekView.submit()` in [line 27](https://github.com/MikibeMiki/WeekViewIssue/blob/de228cbc6c09717c09d22967651d9ad5e7b1a192/app/src/main/java/com/example/weekviewissue/ui/main/MainFragment.kt#L27) _and_ the `OnLoadMoreListener` causes it. Usually, using only one of them should be sufficient (see [wiki](https://github.com/MikibeMiki/WeekViewIssue/blob/de228cbc6c09717c09d22967651d9ad5e7b1a192/app/src/main/java/com/example/weekviewissue/ui/main/MainFragment.kt#L27)). Could you explain why you feel the need to use both?

**Comment by MikibeMiki** [comment]
First submit on line 27 is used for setting already shown data. 
Submit on line 35 adds new data when the range is changed.

Let us say that I used LiveData, then I would observe on line 27, and send load command on line 35, which will then call line 27/

**Comment by thellmund** [comment]
I understand your intention. However, I think the call to `weekView.submit()` on line 27 is not necessary. Instead, if you want to use paged loading via the `OnLoadMoreListener`, you should submit them once the user scrolls to that range. Do you know what I mean?

**Comment by MikibeMiki** [comment]
But if I want to restore a view after device is rotated, I need line 27, right?

**Comment by thellmund** [comment]
WeekView should automatically restore its state on configuration changes.

**Comment by MikibeMiki** [comment]
Ok, I'll try it in that way.
Btw, thank you for great library.
