### ISSUE TITLE
Chip disappear when scrolling

### ISSUE THREAD

**Issue by MohammadB72** [thellmund/Android-Week-View#119]
**Describe the bug**
i define a chip in weekView, but it disappear when scrolling

👇👇 Follow the steps below to make it happen again
https://youtu.be/adjUmN6GuZM

**Comment by thellmund** [comment]
Can you provide a sample app with the code that causes this behavior? I’ll take a look soon.

**Comment by MohammadB72** [comment]
in your sample app this problem has been occurred too.

[https://www.youtube.com/watch?v=9gdP18qce8k&feature=youtu.be](url)

**Comment by thellmund** [comment]
I pushed a fix to `develop`. Could you give it a try by switching to `implementation "com.github.thellmund.Android-Week-View:core:develop-SNAPSHOT"` and then let me know if it resolves your issue?

**Comment by thellmund** [comment]
Closing this issue. Feel free to re-open if you continue to experience any related issues.

**Comment by vikasj** [comment]
I'm having this issue as well on the latest release. Events disappear when scrolling to a different week and then back to the current week.

**Comment by thellmund** [comment]
Can you provide me with a sample app or a recording that showcases the incorrect behavior?
