### ISSUE TITLE
Cloned events do not have their data property set

### ISSUE THREAD

**Issue by Menthuss** [thellmund/Android-Week-View#12]
When the library clones and modifies WeekViewEvent objects for events that span multiple days, the cloned event will not have it's data property set. When the user then taps the event, the library will throw an exception.

The following function is responsible for this:

List<WeekViewEvent<T>> splitWeekViewEvents() {

        if (!isSameDay(clonedEndTime)) {
            clonedEndTime = (Calendar) startTime.clone();
            clonedEndTime.set(Calendar.HOUR_OF_DAY, 23);
            clonedEndTime.set(Calendar.MINUTE, 59);

            WeekViewEvent<T> event1 = new WeekViewEvent<>(id, title, startTime, clonedEndTime, location, isAllDay);
            event1.setColor(color);
            events.add(event1);

            // Add other days.
            Calendar otherDay = (Calendar) startTime.clone();
            otherDay.add(Calendar.DATE, 1);

            while (!DateUtils.isSameDay(otherDay, this.endTime)) {
                Calendar overDay = (Calendar) otherDay.clone();
                overDay.set(Calendar.HOUR_OF_DAY, 0);
                overDay.set(Calendar.MINUTE, 0);

                Calendar endOfOverDay = (Calendar) overDay.clone();
                endOfOverDay.set(Calendar.HOUR_OF_DAY, 23);
                endOfOverDay.set(Calendar.MINUTE, 59);

                WeekViewEvent<T> eventMore = new WeekViewEvent<>(id, title, overDay, endOfOverDay, location, isAllDay);
                eventMore.setColor(color);
                events.add(eventMore);

                // Add next day.
                otherDay.add(Calendar.DATE, 1);
            }

            // Add last day.
            Calendar startTime = (Calendar) this.endTime.clone();
            startTime.set(Calendar.HOUR_OF_DAY, 0);
            startTime.set(Calendar.MINUTE, 0);

            WeekViewEvent<T> event2 = new WeekViewEvent<>(id, title, startTime, this.endTime, location, isAllDay);
            event2.setColor(color);
            events.add(event2);
        } else {
            events.add(this);
        }

        return events;
    }

Specifically, this way of cloning WeekViewEvents causes null values for the data property: `WeekViewEvent<T> eventMore = new WeekViewEvent<>(id, title, overDay, endOfOverDay, location, isAllDay);`

Can easily be reproduced by modifying one of the events in the sample project to span multiple days and then tapping on the event.

**Comment by thellmund** [comment]
Addressed with the latest commit 2f741ebaab07e47d817eb0883fdceaf0ecf6aa3a. Will push version 3.1.2 containing this fix tonight.
