### ISSUE TITLE
Project in java

### ISSUE THREAD

**Issue by alena424** [thellmund/Android-Week-View#120]
Hello,

I have my project to school written in java and like very much your library. I am struggling with converting your kotlin sample project to java to make it work. Do you have some examples written in java using this library? It would help so much. Thank you.

**Comment by thellmund** [comment]
You can have a look at [LegacyActivity](https://github.com/thellmund/Android-Week-View/blob/develop/sample/src/main/java/com/alamkanak/weekview/sample/LegacyActivity.java) – it’s written in Java.
