### ISSUE TITLE
Add icons/images in the events

### ISSUE THREAD

**Issue by Mauker1** [thellmund/Android-Week-View#121]
There are two things that I miss on the lib. 

First of them is the possibility to set an image as the event background, as it's possible on Google Calendar.

E.g.: 
![image](https://user-images.githubusercontent.com/2752808/67884370-7ca39300-fb24-11e9-976d-155c9827d4aa.png)

The second thing is that currently, we can only add text in the events, it might be a good idea to add icons/emojis to help the user find events faster by glancing at them as[ this guy suggested with emojis on his post](https://www.techrepublic.com/article/tweak-your-google-calendar-for-clarity/).

![image](https://user-images.githubusercontent.com/2752808/67883984-d2c40680-fb23-11e9-86ae-b443ba67c6da.png)

**Comment by thellmund** [comment]
Hi @Mauker1, including emojis in the event title is already possible. I just confirmed that they are displayed correctly. Was that what you meant? 

I’m a bit hesitant regarding the idea of adding background images to events. Google Calendar only does that in the agenda view, but not in the day, week, and month views. While the event height is fixed for the agenda view, that’s not the case for the latter. I’m not sure how useful a background image would be if the event itself is only a couple of pixels high. Let me know if you have a different take on this :slightly_smiling_face:

**Comment by Mauker1** [comment]
About the Emojis, are you using the EmojiCompat? I reckon that some devices might not display some emojis correctly depending on the Android version or device vendor.

More about this here: https://developer.android.com/guide/topics/ui/look-and-feel/emoji-compat

Regarding the background images, you have a good point there :)

**Comment by thellmund** [comment]
I’ll have a look at EmojiCompat.

**Comment by thellmund** [comment]
I worked on an implementation in `th/emoji`. Let me know what you think.

**Comment by thellmund** [comment]
Added in #126.

**Comment by tlozovyi** [comment]
Oh wow, this change added 10 Mb to the app size which is huge.
Is it possible to make this change optional?
It almost doubles app size.

**Comment by thellmund** [comment]
Sure, I can have a look at that. Can you create a separate issue for that?

**Comment by tlozovyi** [comment]
Sure, thanks!
