### ISSUE TITLE
Allow selection of events

### ISSUE THREAD

**Issue by Mauker1** [thellmund/Android-Week-View#122]
It would be nice to have a "selected state" on the events, allowing single or multiple events selections. That would make easier to manipulate those events (deleting them for instance).

**Comment by thellmund** [comment]
I think that should be handled outside the library. For instance, imagine you have a data class like this: 

```kotlin
data class MyEvent(
  val title: String, 
  val location: String, 
  // ...
  val isSelected: Boolean = false
) : WeekViewDisplayable<MyEvent>
```

You apply the appropriate style in `WeekViewEvent.Style.Builder` to indicate the selected state:

```kotlin
data class MyEvent(...) : WeekViewDisplayable<MyEvent> {
  override fun toWeekViewEvent(): WeekViewEvent<MyEvent> {
    val borderColor = if (isSelected) color1 else color2
    val style = WeekViewEvent.Style.Builder()
      .setBorderColor(borderColor)
      .build()
    return ...
}
```

Whenever the user clicks (or long-clicks, or whatever) an event, update its `isSelected` property:

```kotlin
val myEvents: MutableList<MyEvent> = ...
weekView.setOnEventClickListener { event, bounds -> 
  val newEvent = event.copy(isSelected = !event.isSelected)
  val index = myEvents.remove(event)
  myEvents.add(index, newEvent)
  weekView.submit(myEvents)
}
```

What do you think about this approach? Is there anything that’s missing to fulfill your use case?

**Comment by Mauker1** [comment]
Ohh, that's really a very nice solution to this problem. I like it. Thanks!
