### ISSUE TITLE
Widget Week View

### ISSUE THREAD

**Issue by alena424** [thellmund/Android-Week-View#124]
Can you help me how can I use this week view layout for an android widget?

Thank you very much for advice (beginner of Android)

**Comment by thellmund** [comment]
You can’t use custom views in a widget (see [documentation](https://developer.android.com/guide/topics/appwidgets/index.html#CreatingLayout)). Apparently there exists a workaround by using `view. getDrawingCache()` (see [StackOverflow](https://stackoverflow.com/questions/4062559/android-appwidget-with-custom-view-not-working)), but I haven’t tried that.
