### ISSUE TITLE
How to Add a Single Event

### ISSUE THREAD

**Issue by GianniLane** [thellmund/Android-Week-View#125]
Probably a stupid question, but how do I add just one event? the code from the sample project only shows how to create events that repeat every month on the dayOfMonth.

events += newEvent(
            id = idOffset+1,
            year = year,
            month = month,
            dayOfMonth = 6,
            hour = 16,
            minute = 0,
            duration = 60,
            color = color1
        )

I thought it could be done by changing the value of month to, say 12 for December, but that doesn't work.

**Comment by thellmund** [comment]
No, not a “stupid question” at all. If there is something that is not easily understandable, then it’s my fault :)

You can add a single event like so: 
```kotlin
val event = createEvent(...)
weekView.submit(list of(event))
```

Check out [this section](https://github.com/thellmund/Android-Week-View/wiki#4-provide-events-to-weekview) on the wiki page for more info.
