### ISSUE TITLE
MonthLoader requests wrong month

### ISSUE THREAD

**Issue by tylermarien** [thellmund/Android-Week-View#13]
When MonthChangeListener.onMonthChange is called, it appears to be receiving the wrong startDate and endDate (they are for the next month).

The error is in MonthLoader.onLoad.

```
        final int year = periodIndex / 12;
        final int month = periodIndex % 12 + 1;

        final Calendar startDate = DateUtils.withTimeAtStartOfDay(today());
        startDate.set(Calendar.YEAR, year);
        startDate.set(Calendar.MONTH, month);
        startDate.set(Calendar.DAY_OF_MONTH, 1);

        final int maxDays = startDate.getActualMaximum(Calendar.DAY_OF_MONTH);

        final Calendar endDate = DateUtils.withTimeAtEndOfDay(today());
        endDate.set(Calendar.YEAR, year);
        endDate.set(Calendar.MONTH, month);
        endDate.set(Calendar.DAY_OF_MONTH, maxDays);

        final List<WeekViewDisplayable<T>> displayableItems =
                onMonthChangeListener.onMonthChange(startDate, endDate);
```

It is my understanding that `startDate.set(Calendar.Month, month)` is [0 indexed](https://developer.android.com/reference/java/util/Calendar.html#MONTH), so ` final int month = periodIndex % 12 + 1;` should actually be `final int month = periodIndex % 12;`.

**Comment by thellmund** [comment]
You’re right. Part of the problem was that `FakeEventsDatabase` in the sample app always used `month-1` for creating events, so it appeared to work correctly.

I’ve just pushed a fix and will deploy the new version.
