### ISSUE TITLE
Event clicks not always working after zooming in

### ISSUE THREAD

**Issue by Mkryglikov** [thellmund/Android-Week-View#131]
Event clicks not always working after zooming in. Example is on gif
Looks like problem in WeekViewGestureHandler.findHitEvent() - candidates is empty.

 - Android version: Android 9.0 on Android Studio emulator with Pixel 3a preset.
 - WeekView version: 4.0.1

![Sample](https://i.ibb.co/NY3Q7XB/untitled.gif)

![Debugging](https://i.ibb.co/nCJ4y5v/Annotation-2020-01-28-100755.jpg)

**Comment by thellmund** [comment]
Thanks for reporting this! I fixed the issue in cdb65a4edfe1319982f4e081a3f43082bdf0601f and will push version 4.1.3 now.
