### ISSUE TITLE
Custom Layout

### ISSUE THREAD

**Issue by rudyromer** [thellmund/Android-Week-View#134]
There is no way to make a custom layout for a WeekViewEvent ?

**Comment by thellmund** [comment]
What exactly do you mean? You can customize certain aspects of a WeekViewEvent, such as the background color, border width and color, strike-through, and the font.

**Comment by rudyromer** [comment]
Yes for these aspects but if i want to add something like an view just on left ( on all the WeekViewEvent height and only 2dp  for the width) to indicate a status.

**Comment by thellmund** [comment]
All right, let me think about how to implement this. Maybe something like this for adding a vertically centered drawable on the left-hand side?

```kotlin
val style = WeekViewEvent.Style.Builder()
  .setDrawableLeft(resourceId = R.drawable.some_image, gravity = Gravity.CENTER)
  .build()
```

Can you provide me with a mock-up of how you’d like the view to look like? Also, WeekView already supports emojis, so maybe you can use that as an intermediate solution.

**Comment by rudyromer** [comment]
Something like that. Thinks for your quick answer !

<img width="327" alt="Capture d’écran 2020-02-07 à 13 54 57" src="https://user-images.githubusercontent.com/4647637/74031458-d92f0d80-49b1-11ea-940c-5bd9acad7c25.png">

**Comment by rudyromer** [comment]
Hi i try 
`val style = WeekViewEvent.Style.Builder()
  .setDrawableLeft(resourceId = R.drawable.some_image, gravity = Gravity.CENTER)
  .build()`
but method `setDrawableLeft()` doesn't exist ?

**Comment by thellmund** [comment]
My comment above is just an example of how the feature _could_ be implemented. It’s not part of the library yet.

**Comment by Harrybisht3** [comment]
How to customize the Event view. Like I want to add images buttons on the EventChip?
