### ISSUE TITLE
java.lang.IllegalStateException: Required value was null.

### ISSUE THREAD

**Issue by michaelbukachi** [thellmund/Android-Week-View#135]
**Describe the bug**
Setting the events for current month only causes a `java.lang.IllegalStateException: Required value was null.`

**To Reproduce**
Clone the repo from [here](https://github.com/michaelbukachi/WeekViewTest) and run app. 

**Expected behavior**
Events to be shown on the WeekView

**Additional context**
 - Android version: Android 10
 - WeekView version: 4.0.1

**Comment by thellmund** [comment]
Thanks for reporting this! I fixed the issue in 09e10d3221efdf8ca30eaf85407361258482c36b and will push a new version now.

**Comment by michaelbukachi** [comment]
Awesome! I really appreciate the quick response.
