### ISSUE TITLE
How to customize the margin of the drawn event

### ISSUE THREAD

**Issue by neilpototffufm** [thellmund/Android-Week-View#141]
I'm looking for a way to set the margin of the drawn shape. Is there any way to do this? Because I saw this when I'm viewing into Day View, the event has some side distance from the time column, left to right.
![Screenshot_20200324-220910_Android Week View](https://user-images.githubusercontent.com/60129405/77434758-4ee52080-6e1c-11ea-9295-162f79f92533.jpg)

**Comment by thellmund** [comment]
You can set `singleDayHorizontalMargin` (see [here](https://github.com/thellmund/Android-Week-View/wiki/Customization-Attributes#event-margins-what-is-that)).

**Comment by neilpototffufm** [comment]
> You can set `singleDayHorizontalMargin` (see [here](https://github.com/thellmund/Android-Week-View/wiki/Customization-Attributes#event-margins-what-is-that)).

but that works only with single day right? How about for multiple days like 3, 5 or 7-day columns?

**Comment by thellmund** [comment]
For multi-day views, you can set `columnGap` which represents the gap between events of different dates. Does that help for your use case?

**Comment by neilpototffufm** [comment]
I think it does, but only the right side is adjusted, the left margin is not
![Screenshot_20200325-095955_Android Week View](https://user-images.githubusercontent.com/60129405/77494033-a36db780-6e7f-11ea-8cc2-7cafa84805eb.jpg)
