### ISSUE TITLE
Add the ability to switch between 12/24 hours in timeline

### ISSUE THREAD

**Issue by machendos** [thellmund/Android-Week-View#142]
Not all countries live in 12-hour format.
It would be great to be able to set an additional property like `timeFormat` in `WeekWiew` xml. There it would be possible to indicate in which time format labels are displayed in time column

**Comment by thellmund** [comment]
I’m from on of those countries 😉You can use `DateTimeFormatter` to specify your own date and time format (see [the wiki](https://github.com/thellmund/Android-Week-View/wiki/Listeners#datetimeinterpreter)).
