### ISSUE TITLE
Crash issue: TypeCastException when construct SaveState

### ISSUE THREAD

**Issue by shuirna** [thellmund/Android-Week-View#143]
**Describe the bug**
Crash issue: TypeCastException when construct SaveState

This issue is observed from [Firebase](https://firebase.google.com/)

Caused by kotlin.TypeCastException
null cannot be cast to non-null type java.util.Calendar
com.alamkanak.weekview.SavedState.<init> (SavedState.kt:26)
com.alamkanak.weekview.SavedState$Companion$CREATOR$1.createFromParcel (SavedState.kt:38)
com.alamkanak.weekview.SavedState$Companion$CREATOR$1.createFromParcel (SavedState.kt:37)
android.os.Parcel.readParcelable (Parcel.java:2990)
androidx.databinding.DataBindingUtil.setContentView (DataBindingUtil.java:284)

The SaveState instance maybe construct with a null Calendar. 

**Additional context**
 - Android version: [Android 10  about 55%]
 - WeekView version: [4.0.1]

**Comment by thellmund** [comment]
Thanks for contributing, @shuirna!
