### ISSUE TITLE
Add and show a time period as blocked time

### ISSUE THREAD

**Issue by gopalgupta93** [thellmund/Android-Week-View#150]
My app has staff service bookings and staff blocked time, in blocked time no booking can be added.  

If a staff has blocked time on perticular date and time period,
**I want to show blocked time period on calendar,** So for a particular time period (for example- 10:00AM to 11:00AM) it is showing as blocked in diagonal lines on time hour grid.
I am attaching a screen.
How can i do this. i need to add diagonal lines in a time grid.

![image_block_time](https://user-images.githubusercontent.com/17352145/81971406-a6df1d00-963e-11ea-9787-c84cd79df507.png)

**Comment by vikasj** [comment]
I did this by modifying the `DayBackgroundDrawer` by drawing half hour background blocks.
It would be nice to have this as a feature :)

`  override fun draw(
        drawingContext: DrawingContext,
        canvas: Canvas
    ) {
        drawingContext.dateRangeWithStartPixels.forEach { (date, startPixel) ->
            val startX = max(startPixel, config.timeColumnWidth)

            // Check if we want to show business hours
            if (config.showBusinessHours) {
                val calendar = date.copy()
                calendar.set(Calendar.HOUR_OF_DAY, 0)
                calendar.set(Calendar.MINUTE, 0)
                calendar.set(Calendar.SECOND, 0)
                calendar.set(Calendar.MILLISECOND, 0)
                val startDate = date.copy()
                var startY = config.headerHeight + config.currentOrigin.y
                while(calendar.get(Calendar.DATE) == startDate.get(Calendar.DATE)) {
                    drawHalfHourBackground(calendar, startX, startPixel, startY, canvas)
                    calendar.add(Calendar.MINUTE, 30)
                    startY += config.halfHourHeight
                }
            } else {
                drawDayBackground(date, startPixel, canvas)
            }
        }
    }

   /**
     * Draw Half Hour Background
     * @param date calendar date of half hour block
     * @param startX start X point of half hour block
     * @param startPixel start X point of the calendar column
     * @param startY start Y point of the half hour block
     * @param canvas canvas to draw on
     */
    private fun drawHalfHourBackground(
        date: Calendar,
        startX: Float,
        startPixel: Float,
        startY: Float,
        canvas: Canvas
    ) {
        if (config.widthPerDay + startPixel - startX <= 0) {
            return
        }
        val right = startPixel + config.totalDayWidth

        // check if the date is during business hours for each day
        val isDuringBusinessHours = when (date.dayOfWeek) {
            Calendar.SUNDAY -> {
                duringBusinessHours(date, view.businessHours?.cal0)
            }

            Calendar.MONDAY -> {
                duringBusinessHours(date, view.businessHours?.cal1)
            }

            Calendar.TUESDAY -> {
                duringBusinessHours(date, view.businessHours?.cal2)
            }

            Calendar.WEDNESDAY -> {
                duringBusinessHours(date, view.businessHours?.cal3)
            }

            Calendar.THURSDAY -> {
                duringBusinessHours(date, view.businessHours?.cal4)
            }

            Calendar.FRIDAY -> {
                duringBusinessHours(date, view.businessHours?.cal5)
            }

            Calendar.SATURDAY -> {
                duringBusinessHours(date, view.businessHours?.cal6)
            }

            else -> false
        }

        // don't draw a busy background if date is DURING business hours
        if (isDuringBusinessHours) {
            return
        } else {
            // create the rectangle with points in which to draw the bitmap in
            val rectF = RectF()
            rectF.set(startX, startY, right, startY + config.halfHourHeight)
            if (view.businessHoursBackground != null) {
                canvas.drawBitmap(view.businessHoursBackground!!, null, rectF, null)
            }
        }
    }`

**Comment by thellmund** [comment]
Hi @gopalgupta93 👋 As @vikasj mentioned, you’d need to create your own fork in order to do this right now. But I’m considering adding this as a feature.

Some questions about your use case:
1. Are the blocked times always at a specific time (e.g. every Thursday from 10 to 11 AM) or random?
2. How would you want to indicate the blocked time? I’m wondering if simply using a specific color would be enough or if WeekView should also take in a bitmap for the background?
3. What should happen if the user taps in this area?

**Comment by miggitymac** [comment]
@thellmund - We're also running into a similar use-case. It would be helpful if we could set aside blocks of time that can not have events scheduled and show the unavailable times as a color or bitmap. 
We are doing something similar on iOS using a different library. Below are some screenshots of what we have done on iOS. 

![Screen Shot 2020-09-29 at 15 49 48](https://user-images.githubusercontent.com/8602836/94615043-b6b57180-026c-11eb-8bac-867f1d45ebb7.png)

![Screen Shot 2020-09-29 at 15 57 52](https://user-images.githubusercontent.com/8602836/94615058-bae18f00-026c-11eb-8218-6db57f30c25d.png)

**Comment by thellmund** [comment]
Hi @miggitymac – thanks for the examples in the screenshots! Would you always include a note in the unavailable time block (e.g. “Reserved”)?

**Comment by miggitymac** [comment]
@thellmund - Thanks for the quick response! For our use case, there are times when a facility can't have anything booked due to open and closed hours (business hours). 

But, then there are times when the space that needs to be booked is already `Reserved` during normal business hours and that is the reserved block you see in the example. In that case, someone else has already taken that blocked time for the day, so no other user should be able to schedule.

By adding in these features, you could make the calendar very useful for businesses hoping to manage bookings and reservations for their clients.

**Comment by thellmund** [comment]
I experimented with a few approaches for the last few days. Currently, I’m favoring to replace `WeekViewEvent<T>` with a sealed class `WeekViewEntity`, which can be `Event<T>` or `BlockedTime`. Both will possess their own `Builder` helpers, so you wouldn’t need to provide event-specific properties (e.g. `location` or `data`) to a blocked time. 

You can have a look at the current progress in #180. Let me know what you think from an API perspective. I’m trying to make sure that the change doesn’t break `toWeekViewEvent()`, which will be replaced by `toWeekViewEntity()`. For reference, the sample’s `Event` data class uses the new `toWeekViewEntity()`, while `ApiEvent` uses the deprecated `toWeekViewEvent()` without any noticeable constraints to the library user.

**Comment by thellmund** [comment]
Hi @miggitymac – I have the implementation in a state where I’m quite happy with it. If you have some time, I’d love for you to have a look and let me know if the API works well for you. I want to confirm that it works for a real project, not just my little sample app.

You’d need to add `implementation 'com.github.thellmund.Android-Week-View:core:th~blockedTimes-SNAPSHOT'` to your `build.gradle` to use the branch version.

**Comment by thellmund** [comment]
Merged into master now. This will go out with version 5.1 soon.
