### ISSUE TITLE
Wrong PastFuture detection when xml attr: "minHour" is set

### ISSUE THREAD

**Issue by rafi0101** [thellmund/Android-Week-View#155]
**Description**
When you use the xml attributes: 'showDistinctPastFutureColor="true"' and 'minHour="x"' at the same time, the background color for the past time is shown for: current time + x (defined in minHour).
See example below.

**To Reproduce**
In this Example is used your sample app, and the "LimitedActivity"
1. Go to [activity_limited.xml](https://github.com/thellmund/Android-Week-View/blob/master/sample/src/main/res/layout/activity_limited.xml)
2. Add 'app:showDistinctPastFutureColor="true"' as attribute to the WeekView
3. Install App, and you have the same picture as in the screenshot

**Expected behavior**
when you use those 2 attributes at the same time, the background color for the past should be calculated correctly

**Screenshot**
In this screenshot the minHour is set to 8

![Screenshot_20200609-105736](https://user-images.githubusercontent.com/43086854/84127935-2a263f80-aa40-11ea-8bb4-e0715743185b.jpg)

**Additional context**
 - Android version: 10
 - WeekView version: 4.1.6

**Comment by thellmund** [comment]
Thanks for reporting this. I fixed it in c5b74af74415d560e54240546e2ea7dd798bb2be, which will be included in the next release.
