### ISSUE TITLE
Add repeatable event feature

### ISSUE THREAD

**Issue by Andrey-Morenkov** [thellmund/Android-Week-View#157]
Add feature that event could repeat on specific day of week (i.e event which occurs every monday and friday, for example)

**Comment by thellmund** [comment]
Appreciate the idea, but I don’t believe that this should be handled by the library. Instead, if you want to display a repeated event, you should provide each repetition as a separate event via `WeekView#submit`.

**Comment by Andrey-Morenkov** [comment]
I have checked the code and seems this is really impossible to implement this feature in current code. I just wanted to know your opinion about this because maybe i have missed something in the code structure...
okay, thanks for reply

**Comment by Andrey-Morenkov** [comment]
> Appreciate the idea, but I don’t believe that this should be handled by the library. Instead, if you want to display a repeated event, you should provide each repetition as a separate event via `WeekView#submit`.

I checked the code and detected that this is impossible to implement this feature in current code, but i wanted to see your opinion about this because maybe i have missed something...
Okay, thanks for your reply.
