### ISSUE TITLE
Can I just change Sunday and Saturday TextColor? And fix weekview always show Sunday until Saturday? 

### ISSUE THREAD

**Issue by kid3652** [thellmund/Android-Week-View#158]
Hi,
Because Saturday and Sunday is holiday, so I want to make the TextColor red.
But it seems to can use mWeekView.setHeaderRowTextColor(R.color.red);  to change all TextColor.
Is some function I ignore?
And can I fix the WeekView HeaderRow always show the order Sunday,Monday,Tuesday....Saturday?

**Comment by Andrey-Morenkov** [comment]
> And can I fix the WeekView HeaderRow always show the order Sunday,Monday,Tuesday....Saturday?

It has "firstDayOfWeek" parameter (you can find it in xml attributes)
P.s seems by default this order depends on your locale?

**Comment by kid3652** [comment]
> It has "firstDayOfWeek" parameter (you can find it in xml attributes)
> P.s seems by default this order depends on your locale?
Hi ,Andrey-Morenkov, thanks for your answer.
I have tried it after you answered.
But it's not work,the first day will be changed to other day of week after srcoll the view.
My xml code is this:
<com.alamkanak.weekview.WeekView
        android:id="@+id/weekView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:defaultEventColor="@color/black"
        app:eventTextColor="@color/white"
        app:timeColumnTextSize="12sp"
        app:hourHeight="60dp"
        app:timeColumnPadding="8dp"
        app:timeColumnTextColor="@color/red"
        app:timeColumnBackgroundColor="@color/white"
        app:headerRowPadding="12dp"
        app:columnGap="8dp"
        app:numberOfVisibleDays="7"
        app:firstDayOfWeek="sunday"
        app:headerRowBackgroundColor="@color/white"
        app:dayBackgroundColor="@color/white"
        app:todayBackgroundColor="@color/white" />

and java code is just mWeekView = (WeekView) view.findViewById(R.id.weekView);  in Fragment.

**Comment by kid3652** [comment]
I seems to ask a stupid question.
I find the answer :

1. Weekend color can change by attributes* `futureWeekendBackgroundColor` and `pastWeekendBackgroundColor` when 
   showDistinctWeekendColor is true.
=> But after I try,it's no use. I still not know why. 

2.First day of the week  is used only when the week view is first drawn. It does not of any effect after user starts scrolling 
  horizontally.
=>So it can't  fix weekview always show Sunday until Saturday now.

**Comment by thellmund** [comment]
Hi @kid3652 👋 

1. I’ll add an attribute for `weekendHeaderTextColor` in a future version.
2. Yes, it’s only used when WeekView is first drawn right now. Do you want to preserve the Sunday-to-Saturday range when the user scrolls between weeks?

**Comment by kid3652** [comment]
Hi,@thellmund

1. Thanks for your help and reply.
2. I think " preserve the Sunday-to-Saturday range when the user scrolls between weeks" is a cool funtion but not a must funtion 
   after I deeper use.  So if it’s good, it’s okay without it.

Actually I hope more that allDayEvent can be showed with a scrollview not just a single line .
Because if I use numberOfVisibleDays="7",everyday's width will be samll. 
And if one day has three above things , the event's title will not show and isn't beautiful. 
Like following picture,I have an all-day-event 8/1~8/5,and another all-day-event at 8/1.
![image](https://user-images.githubusercontent.com/57701043/94505670-30823680-023e-11eb-8cc0-34c3c9d8501a.png)
And if 8/1 have three all-day-event will like this.
![image](https://user-images.githubusercontent.com/57701043/94506081-2b71b700-023f-11eb-8958-f72eaa1782a3.png)
But it seems not easy to be realized.

**Comment by thellmund** [comment]
Do you mean that you want to have all-day events shown below each other instead of next to each other?

**Comment by kid3652** [comment]
Yes,I mean like this.(Reference to following picture)
And it's a scrollView,it can scroll when the events more than two. 
(If I am a Boss,I would want to see all employees' calendar. At this situation,it will have many all-day-events. ) 
![image](https://user-images.githubusercontent.com/57701043/94633967-62100600-0301-11eb-8b20-e261a6d2c870.png)

**Comment by thellmund** [comment]
Gotcha. I added two issues (#171 and #175) for this. I’ll close this one.
