### ISSUE TITLE
Swipe horizontally and vertically together，Crash

### ISSUE THREAD

**Issue by malonecoder** [thellmund/Android-Week-View#164]
**Describe the bug**
Swipe horizontally and vertically together. Repeated several times, it will get stuck and then crash, always appearing

**To Reproduce**
1. Go to BaseActivity or other Activity 
2. goto sevenDay view
3. Scroll horizontally and vertically repeate 
4. stuck and then crash 

**Screenshots**

![image](https://user-images.githubusercontent.com/26137185/92546230-a705c700-f284-11ea-8c8f-5dcf9e53559f.png)

**Additional context**
 - Android version: [Android 11]
 - WeekView version: lasted master bruch

**Comment by thellmund** [comment]
Thanks for reporting this! Should be fixed now. I’ll try to get the next version out sometime soon.
