### ISSUE TITLE
New release version

### ISSUE THREAD

**Issue by thelittlefireman** [thellmund/Android-Week-View#166]
Hi, could it be possible to get a new release on jcenter please :)
I actually use the `implementation 'com.github.thellmund.Android-Week-View:core:master-SNAPSHOT'` but gradle try to check if there is a new version every time.

Thanks !

**Comment by thellmund** [comment]
Sure thing! I spent today updating the documentation and polishing the next release. I’ll push out a beta of version 5 tomorrow.

**Comment by thelittlefireman** [comment]
Perfect thanks ;)
