### ISSUE TITLE
How can i get the event's absolution location of Screen?

### ISSUE THREAD

**Issue by malonecoder** [thellmund/Android-Week-View#167]
override fun onEventClick(data: Meeting, bounds: RectF) {
}
this method can return the view's relatively locations of Event bounds,  but i want to get the event's bounds of Screen ,when click the event, show a pop at the event's right or left. hope you can help me if you are free. thanks！

**Comment by thellmund** [comment]
You should be able to get the absolute location by adding `WeekView`’s x and y coordinates to the event bounds.
