### ISSUE TITLE
Events can't be deleted with simpleAdapter

### ISSUE THREAD

**Issue by thelittlefireman** [thellmund/Android-Week-View#172]
**Describe the bug**
Events can't be deleted with SimpleAdapter.

**To Reproduce**
1) Create a SimpleAdapter.
2) Add 10 events by the submit function on this adapter
Events are well displayed.
3) Re-use the submit function to send 0 event (ie : empty list)
Events are still displayed when the should be deleted !

I try to add a weekevent.invalidate() but it doesn't work.

**Expected behavior**
When you set emptylist to SimpleAdapter it should delete all previous events.

Wiki --> 
```
Simple Adapter
This adapter allows to submit a single list of elements to WeekView. Whenever you submit a new list, the previously submitted list will be removed.
```

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Additional context**
 - Android version:SDK Version 30
 - WeekView version: 5.0.0-beta01

**Comment by thellmund** [comment]
Sorry about that. Fixed now and will go out with the next beta.
