### ISSUE TITLE
Show all-day events with full-day width

### ISSUE THREAD

**Issue by thellmund** [thellmund/Android-Week-View#175]
Arrange all-day events vertically instead of horizontally.

**Comment by tlozovyi** [comment]
Arranging all-day events vertically is a great feature. Looking forward to use it!
Will it be the default approach for all-day events?

**Comment by thellmund** [comment]
Not sure yet. Maybe it makes sense to allow both vertical and horizontal arrangements. 

If I’m going with a vertical arrangement, I’m thinking about adding a way to expand and collapse them, just like Google Calendar does for 3+ all-day events on the same date. 

Thoughts?

**Comment by tlozovyi** [comment]
Yes, allowing both would be the best solution.

Also good thought on expanding\collapsing. Would be also nice to have possibility to set min number of items to collapse. E.g. collapse after 2 on small devices or in landscape orientation, or collapse after 4-5 items when device is long.

**Comment by thellmund** [comment]
I worked on this a bit this evening and have a draft pull request open [here](https://github.com/thellmund/Android-Week-View/pull/178). Let me know what you think.

In this draft pull request, I’m only allowing a vertical arrangement, but I’ll add the horizontal one back before merging this.

**Comment by thellmund** [comment]
Closed via #178. Will include it in the next beta, so you can give it a go.
