### ISSUE TITLE
Is it possible to highlight a day if there are any events on that day?

### ISSUE THREAD

**Issue by alokbharti** [thellmund/Android-Week-View#179]
**Is your feature suggestion related to a problem? Please describe.** 
If there are events in a particular day, Can I highlight the text of the day (Ex- FRI 10/01)

**Describe the solution you'd like**
It would be great if I can highlight the text to let my users know that a particular day has some events on it.

**Comment by thellmund** [comment]
That’s not currently possible. However, I want to allow `SpannableString` for the date and time labels in the future. Once that’s possible, you could color it any way you want. 

If you want to contribute, feel free to do so.
