### ISSUE TITLE
PagingAdapter#refresh does not clear the events chip cache

### ISSUE THREAD

**Issue by RemiNV** [thellmund/Android-Week-View#184]
**Describe the bug**
PagingAdapter#refresh does not clear the events chip cache, which can cause events to remain displayed even after calling refresh().

**To Reproduce**
1) Create a PagingAdapter, returning one event
2) On click on the calendar, make it return another event instead, the next day (both days being displayed), and call refresh().

**Expected behavior**
The previous event disappears, the next event appears

**Actual behavior**
The previous event stays there, the next event appears

WeekView version: 5.0.0-beta04

I'm not sure calling eventsChipCache.clear() is the solution there, but at least if my adapter returns unrelated events and I called refresh(), I would not expect the previous events to still be shown.

**Comment by thellmund** [comment]
Thanks for the catch – I have merged a fix. Will get this out to you soon.

**Comment by RemiNV** [comment]
Awesome, thanks !
