### ISSUE TITLE
Adapter eventsProcessor eventChipCache not updated on WeekView (observer) update

### ISSUE THREAD

**Issue by RemiNV** [thellmund/Android-Week-View#187]
**Describe the bug**
The eventsChipCache of the eventsProcessor of an adapter is never updated, even if a different WeekView (with a different eventsChipCache) is set as observer

**To Reproduce**
1. Create a WeekView in a fragment, with an adapter hosted by the ViewModel of the fragment's activity
2. Rotate the screen: WeekView is recreated
3. Reset the WeekView adapter to the one kept in the ViewModel
4. Have the adapter send new events

**Expected behavior**
Events are shown

**Actual behavior**
No event shown

**Additional context**
 - WeekView version: HEAD

PR on the way

**Comment by thellmund** [comment]
Hi @RemiNV ✌️ Sorry for the delay in getting back to you – I was thinking about this case and how to address the issue you mentioned. It’s probably easiest to simply keep a single `eventChipsCache` in the adapter that `WeekView` can use whenever necessary. This would simplify the code and also solve your issue.

```kotlin
// In WeekView
var adapter: Adapter<*>?

private val eventChipsCache: EventChipsCache?
  get() = adapter?.eventChipsCache
```

I have pushed a commit with this change. I will therefore close this issue and your pull request, but thanks for bringing my attention to this 🙏👍
