### ISSUE TITLE
Events not displayed if custom TimeZone in Calendar objects

### ISSUE THREAD

**Issue by Guiraudou** [thellmund/Android-Week-View#189]
**Describe the bug**
If I specify a timeZone (not GMT) in Calendar object for start and end date, week view is not displaying events. Is it a bug or did something wrong ?

**To Reproduce**
```
String timestamp = "1601535600";
Calendar calStart = Calendar.getInstance(Locale.getDefault()); // work
Calendar calStart = Calendar.getInstance(TimeZone.getTimeZone("GMT"), Locale.getDefault()); // work
Calendar calStart = Calendar.getInstance(TimeZone.getTimeZone("Europe/Paris"), Locale.getDefault()); // doesn't work
Calendar calStart = Calendar.getInstance(TimeZone.getTimeZone("GMT+2"), Locale.getDefault()); // doesn't work
calStart.setTimeInMillis(Long.parseLong(timestamp)*1000);
return new WeekViewEvent.Builder<>(this)
   [...]
    .setStartTime(calStart)
    .setEndTime(calEnd)
   [...]
```

**Expected behavior**
Display events if specify timeZone like "GMT+2" in Calendar object

**Screenshots**
![Android Emulator - Pixel_2_API_295554](https://user-images.githubusercontent.com/1829782/96703678-6cb73b80-1393-11eb-806a-a918f31ba5d0.jpg)

**Additional context**
 - Android version: [Android 10.0]
 - WeekView version: [4.1.6]

(I try to upgrade to v5.0.0 but there is break changes and I didn't found the doc for replace functions setOnLoadMoreListener and setOnEventClickListener)
Thanks

**Comment by thellmund** [comment]
Hi there ✌️ Can you please provide me with a sample repository that showcases this behavior? As for version 5: [This section](https://github.com/thellmund/Android-Week-View/wiki#3-provide-data-to-weekview) and [this section](https://github.com/thellmund/Android-Week-View/wiki#4-interact-with-weekview) in the wiki should be able to help.

**Comment by Guiraudou** [comment]
Hey !

Thanks you for your reply.
Here is a sample repo :
https://github.com/osimatic/android-test

**Comment by thellmund** [comment]
Hi there 👋  

I took a look at this today and found that WeekView doesn’t handle this case well. I worked on a fix in the branch [`th/189-time-zones`](https://github.com/thellmund/Android-Week-View/commit/ba849f9efea7b0e9c610b1f8d45819bd0f1217e6). You can try it out by using this line in your `build.gradle`:

```groovy
implementation 'com.github.thellmund.Android-Week-View:core:th~189-time-zones-SNAPSHOT'
```

Let me know if this fixes the issue for you.

**Comment by Guiraudou** [comment]
Hello !

Thanks you !
Yes now events are displayed, but the time difference is reversed :
![image](https://user-images.githubusercontent.com/1829782/97348074-f2545300-188d-11eb-8488-6e1194119f49.png)

Event 3 is display from 7am to 3pm instead of 11am to 7pm (same error for all time zones)

**Comment by thellmund** [comment]
I can’t reproduce the behavior shown in your screenshot. What timezone are you in?

**Comment by Guiraudou** [comment]
You don't see the same thing with the sample repo (https://github.com/osimatic/android-test) ?
Timezone is "GMT+2" for Event 3 and "Europe/Paris" for Event 4.
But it's the same for any timezone, example for "America/Los_Angeles" (Event 4 on the below screenshot)

![image](https://user-images.githubusercontent.com/1829782/97410520-798ddf00-18ff-11eb-8694-b89ed113e96f.png)

The time Los Angeles is -8 hours from UTC, here the event is displayed +8 hours from UTC
So the time difference from UTC is just reversed.
I would like to help and contribute but sorry I'm not used to Kotlin :/

There is the real date period in the name of event to help, date period it should be shown in weekview

**Comment by Guiraudou** [comment]
I search a little bit and I think that the problem is in your fonction  convertedToDefaultTimeZone in CalendarExtension.kt :

You write :
val offset = TimeZone.getDefault().rawOffset - timeZone.rawOffset
instead of
val offset = TimeZone.getDefault().rawOffset + timeZone.rawOffset

And I'm not sure everything is good with this code.
For example for Los Angeles, the actual timezone is Pacific Daylight Time (summer time) : UTC-7
Los Angeles will change for standard time ("winter time") on 1st novembre : UTC-8
The rawOffset function give the time difference from UTC without daylight savings.
So instead of use timeZone.rawOffset, I thinks you have to use timeZone.offset and give the date in the parameter :

val offset = TimeZone.getDefault().offset(this.getTime()) + timeZone.offset(this.getTime())

I'm really not sure but I'd like to try this ! (I don't know how sorry ^^)
(i don't know if this is correct in Kotlin, I'm not sure if there is a this but you have the idea, TimeZone.getOffset() in Java must have a java.util.Date in parameter, so you have to use Calendar.getTime() for give the current Calendar object)

**Comment by thellmund** [comment]
I just pushed a new commit to `th/189-time-zones`. Turns out I don’t need any `rawOffset` or `TimeZone.offset()` calls. 

I did add a few events with specific time zones (London, Toronto, Los Angeles) in `EventsDatabase`. They are displayed correctly for me. 

Let me know what you think.

**Comment by Guiraudou** [comment]
Hi !

Thanks.

All event are displayed but with the time of default timezone
![image](https://user-images.githubusercontent.com/1829782/97898596-58caec80-1d38-11eb-938f-059d7a07256e.png)

I'd like to to "force" the time zone of an event : if a event is from 09:00 UTC to 17:00 UTC with time zone "America/Los_Angeles", display event from 02:00am to 10:00am whathever default time zone is.
In the screenshot, event 4 is configured with calendar object with time zone "America/Los_Angeles" and should be displayed from 02:00am to 10:00am
I don't know if this is possible without break existing functionnalities...

What you did before with offset was perfect except bug concerning offset reversed.

**Comment by thellmund** [comment]
Wait, you want to display events as if the user was in that time zone, even if they aren’t? 

As an example: 
- The user’s time zone is GMT.
- WeekView needs to render an event in Los Angeles that starts at 10 AM and ends at 11 AM (both Los Angeles time).
- You want it to be displayed from 10 AM to 11 AM instead of from 6 PM to 7 PM (which would be GMT time)?

Am I understanding you correctly?

**Comment by Guiraudou** [comment]
Yes it's wird.. Now it seems ok, events are displayed so that's better ;)
In PHP we have to specify timezone in order to display datetimes correctly from UTC timestamp..
Thanks you !

**Comment by dsounded** [comment]
@thellmund shouldn't java8 version be affected also ?
