### ISSUE TITLE
When switching views, WeekView scrolls back to current date

### ISSUE THREAD

**Issue by thellmund** [thellmund/Android-Week-View#19]
Switching between views (e.g. from week to day view) resets WeekView to the current date. Instead, it should remain at the first visible day.

**Comment by cs8898** [comment]
In WeekViewConfig.java
```
    void setNumberOfVisibleDays(int numberOfVisibleDays) {
        this.numberOfVisibleDays = numberOfVisibleDays;
        drawingConfig.resetOrigin();
    }
```
while in WeekViewDrawingConfig.java
```
    void resetOrigin() {
        currentOrigin = new PointF(0, 0);
    }
```
probably the code in WeekViewConfig.java can be changed to a recalc of the Origin, based on the oldNumVisibleDays and the newNumVisibleDays
AFAIK there was a function to get the Date of a specific position, based on that there should be the possibility to use the getXOriginForDate in DateUtils.tk created introduced in  #33 
and set the new value as the currentOrigin.x value

**Comment by thellmund** [comment]
Fixed with 56aef3e38f734500f9fd2d16db825f246e8fbbf7

**Comment by cs8898** [comment]
The Current solution working, but the call to resetOrigin Can and should be removed...
Ok it's just setting the Origin to 0 and rescale it back to the old first Visible day...

In WeekViewConfig.java
```
    void setNumberOfVisibleDays(int numberOfVisibleDays) {
        this.numberOfVisibleDays = numberOfVisibleDays;
        drawingConfig.resetOrigin(); // <<<<--- This would be unnecessary
    }
```

Because the Commit 56aef3e will reset to the first Visible Day

**Comment by cs8898** [comment]
The Origin seems sometimes miss calculated...

Should be reconstructable by circling between different perspectives.
Some times the drawer will display half of an other day and is not snapping directly to the correct position...

**Comment by thellmund** [comment]
I’ll remove `drawingConfig.resetOrigin()`. The other issue seems to only occur when you change the text dimension in the time column – I’ll have a look at that, too.
