### ISSUE TITLE
WeekView as weekly schedule

### ISSUE THREAD

**Issue by AndiezSatria** [thellmund/Android-Week-View#190]
Hello, I want to ask some questions with this lib. I want to build a schedule app and display it in week view and I found this great lib. I've already see the sample app and found static activity which what I want to implement it to my app. Instead using date in header, I want to display the day of week, from Monday to Sunday. And also I want to represent event as schedule on that day. I want the weekview view the day statically, event and the column that represent day of week. Is it possible to do it with this lib ?  Hope you understand my words

**Comment by thellmund** [comment]
Hi there 👋

> Instead using date in header, I want to display the day of week, from Monday to Sunday.

You can do this like so: 

```kotlin
weekView.setDateFormatter { date ->
  val dateFormat = SimpleDateFormat("EEEE", Locale.getDefault())
  return dateFormat.format(date.time)
}
```

> And also I want to represent event as schedule on that day. I want the weekview view the day statically, event and the column that represent day of week.

Not sure what exactly you mean. Do you want to show only one day at a time?

**Comment by AndiezSatria** [comment]
Thanks for your response. Basically, what I want is to make the date static (weekview only start from monday to sunday and never change).For the event, I call it schedule but it's still an event. What I see in sample app the event occur based on date but what I want is based on day of week. So the event will always show in weekview even my device already change week, just like schedule.

**Comment by thellmund** [comment]
Gotcha! All of that is possible with WeekView right now. You can start with a configuration similar to `StaticActivity`:
- Set `horizontalScrollingEnabled` to `false`.
- Set `numberOfVisibleDays` to `7`.
- Set `showFirstDayOfWeekFirst` to `true`.

As for the day of week: You’ll need to do the conversion between `day of week` and `date` yourself.
