### ISSUE TITLE
Bad drawing when there is not enough vertical space to draw text in EventChip

### ISSUE THREAD

**Issue by manu8170** [thellmund/Android-Week-View#192]
When there is not enough vertical space to draw the text of an EventChip (bounds height minus 2 times the vertical padding), bounds of this EventChip are empty (CalendarRender.kt, line 86). Since the bounds are empty, the eventChip is not rendered at all (CalendarRender.kt, line 231). So the event is not visible.

In my opinion, the EventChip should be drawn without any text if there is not enough space to draw the text. Otherwise we get some strange side effects like a multi-colums day with an empty column (the column where the EventChip should be drawn).

There is currently a workaround: set the event vertical padding (eventPaddingVertical) to 0.

**Comment by thellmund** [comment]
Can you add a screenshot of such a scenario to this issue?

**Comment by manu8170** [comment]
Hi Thellmund,

Thank you for your interest for this behavior.

Example with an non null eventPaddingVertical :
![image](https://user-images.githubusercontent.com/7500009/97887077-b146bd80-1d29-11eb-94c3-57c125508237.png)

When zooming in :
![image](https://user-images.githubusercontent.com/7500009/97887253-f23ed200-1d29-11eb-8ebc-c1325a86f2c3.png)

Example with eventPaddingVertical=0dp:
![image](https://user-images.githubusercontent.com/7500009/97887559-60839480-1d2a-11eb-882d-b7d9aac8460b.png)


Regards

**Comment by thellmund** [comment]
Thanks! I’ll have a look at that soon.

**Comment by thellmund** [comment]
I pushed a fix in commit 2a40b2da0fffdf50d6aefe890ca6f9cfb2884faf. This will be included in the next release of the library.

Also: If you want to prevent the user from zooming out all the way, you can set the `minHourHeight`.

**Comment by thellmund** [comment]
The new release with the fix is out now.
