### ISSUE TITLE
Brief events are not drawn (related to #192)

### ISSUE THREAD

**Issue by manu8170** [thellmund/Android-Week-View#196]
Hi,

Thank you for release 5.0.1.
Unfortunately this new release doesn't completely fix issue #192. According to me, this is due to CalendarRender.kt line 237: if an event is too brief, there is no entry for it in the array eventLabels, so eventChipDrawer.draw is not called for such an event.

You can see in the [attached file](https://github.com/thellmund/Android-Week-View/files/5493437/video.zip) the current behaviour recorded on a smartphone. At beginning the brief event is not visible even if there is a column reserved for it. Zooming in makes it appear. Surprisingly zooming out keeps it visible, even if it disappears finally (I didn't investigate this effect).

Regards

**Comment by thellmund** [comment]
You’re right. It should be fixed with 5318d66dccff6ad9cdab6b50d0421de0fc83fa46 now.

**Comment by manu8170** [comment]
Hi, I confirm the problem is fixed. Thank you for your responsiveness !
