### ISSUE TITLE
firstVisibleHour returns unexpected value

### ISSUE THREAD

**Issue by FeFelten** [thellmund/Android-Week-View#199]
**Describe the bug**
The method `firstVisibleHour` returns a wrong value, when minHour is not 0.

**To Reproduce**
1. set minHour to a value larger than 0
2. print value of firstVisibleHour now the value can be 0 despite minHour is larger

**Expected behavior**
The offset of minHour is added to firstVisibleHour or at least changing the name of the variable and the documentation that it can be easier to see what the result of it is.

**Additional context**
 - Android version: 11
 - WeekView version: 5.0.3

**Comment by thellmund** [comment]
Do you think the
