### ISSUE TITLE
Simple one week view

### ISSUE THREAD

**Issue by kev7037** [thellmund/Android-Week-View#2]
Hi.
After days of surfing, I found your code. 
What I want is really simple. I want to show a weekly plan in a week view. The plan only changes every year so there is no need to show other dates. Also, events will be added from database and the user should not be able to add a new event.
Can you help me with this?

**Comment by kev7037** [comment]
well, thanks for quick response.
I've tried your code and it's kind of what I'm looking for.
now that I've added the code from sample project to my project, I'm facing with an error

> Attempt to invoke interface method 'double com.alamkanak.weekview.data.WeekViewLoader.toWeekViewPeriodIndex(java.util.Calendar)' on a null object reference

I've added `apiclient` and `database` files from your project and codes of staticActivity to one of the fragments I'm using. Also some of overrides came up with this error:
`Method does not override method from its superclass`

**Comment by thellmund** [comment]
@kev7037 Did you remember to set a `MonthChangeListener` on the `WeekView`?

**Comment by kev7037** [comment]
I had to use lots of codes I didn't want to insert to my project but it's ok working now. thanks.
One more question. If the event title is `something link this` , user would see:

> som
> ethi
> ng
> like
> this

Is it possible to change it to wrap by word?

**Comment by thellmund** [comment]
Could you upload a screenshot of this to help me understand the context?

**Comment by kev7037** [comment]
[This is it](https://ibb.co/doeCFL).

And one last question, how can I set specific date for the `weekview`?
I'm creating events in `FakeEventsDatabase` and I want a way to set start day of `weekview` to be always for example 08/16/2018. 

I want to use something like ` startTime.set(Calendar.DAY_OF_MONTH, 16);`  (from Aug 16th to 22nd,  2018)

**Comment by thellmund** [comment]
I don’t speak this language, which makes it impossible for me to see exactly what is wrong. Please upload a screenshot in English. 

Regarding the fixed start date: I’ll take a look in the next few days.

**Comment by kev7037** [comment]
Hello again
In case anyone wants to show **the same data in weeks**: I used 
`currentDateTimeString = DateFormat.getDateTimeInstance().format(new Date());`
`int todayIntValue = Integer.parseInt(currentDateTimeString.split(" ")[0].trim());`
and a switch case to calculate different values for different days as weekview starting day is not static

------

I have one more question.
Is it possible to only show a range of hours like 7:00 to 20:00?

**Comment by thellmund** [comment]
Showing only a range of hours is something that I have planned, but I can’t yet say when it will be implemented.
