### ISSUE TITLE
EmptyViewLongClick doesn't work

### ISSUE THREAD

**Issue by Gnuhry** [thellmund/Android-Week-View#201]
The onEmptyViewLongclick don't work in my application. I don't know if it's my problem or a bug.

All other ClickListener are working.

![grafik](https://user-images.githubusercontent.com/31627179/99150954-19858f80-2698-11eb-89ad-227d23267028.png)

 - WeekView version: [5.0.3]

**Comment by thellmund** [comment]
Hi @Gnuhry! Looks like a bug sneaked in there. I have fixed it and will release it with the next version.

**Comment by Gnuhry** [comment]
Thank you for the fast answer

**Comment by thellmund** [comment]
I released the fix with version 5.1.0 just now.
