### ISSUE TITLE
Hours text in time column is visible behind the header

### ISSUE THREAD

**Issue by tlozovyi** [thellmund/Android-Week-View#202]
**Describe the bug**
Time in time column is visible behind the header. At the same time event chips are hidden when they are scrolled behind the header.

**To Reproduce**
1. Open WeekView
2. Scroll down to place hours text behind the header
3. Observe hours text behind the header

**Expected behavior**
Hours text in time column should be hidden behind the header.

**Actual behavior**
Time in time column is visible behind the header

**Screenshots**
![device-2020-11-18-115017](https://user-images.githubusercontent.com/9742534/99514758-c4e25d00-2994-11eb-8e9b-5f024467838b.png)

**Additional context**
 - Android version: 21+
 - WeekView version: 5.0.2

**Comment by thellmund** [comment]
Are you by any change using `Color.TRANSPARENT` as your header background color?

**Comment by tlozovyi** [comment]
Indeed, setting solid color solved the problem. Thanks!

**Comment by thellmund** [comment]
Awesome! Just to be sure, I have limited the drawing to just the time column in 649bfdc6e22489b3eda0f41bae0f323d9b815126 so that you can use a transparent color again 😉

**Comment by tlozovyi** [comment]
Wow, that's great, good job, thanks!
