### ISSUE TITLE
Make emoji library usage optional

### ISSUE THREAD

**Issue by tlozovyi** [thellmund/Android-Week-View#203]
At the moment WeekView library uses emoji-bundled dependency which adds almost 10Mb to app size (Which is huge).

If it is possible making this library optional would be nice. E.g. in a same way as with jodatime adapter.

**Comment by thellmund** [comment]
I didn’t realize the library was this large. I’ll extract it into an optional module.

**Comment by thellmund** [comment]
Will send this out with version 5.1.0 in a few minutes.
