### ISSUE TITLE
5.2.0 - Unauthorized

### ISSUE THREAD

**Issue by Gnuhry** [thellmund/Android-Week-View#205]
I don't know a lot about gradle or jitpack, but i think there is a autorization problem with the newest version.

```
* What went wrong:
Execution failed for task ':app:checkDebugAarMetadata'.
> Could not resolve all files for configuration ':app:debugRuntimeClasspath'.
   > Could not resolve com.github.thellmund:base:5.2.0.
     Required by:
         project :app > com.github.thellmund.Android-Week-View:core:5.2.0
         project :app > com.github.thellmund.Android-Week-View:emoji:5.2.0
      > Could not resolve com.github.thellmund:base:5.2.0.
         > Could not get resource 'https://jitpack.io/com/github/thellmund/base/5.2.0/base-5.2.0.pom'.
            > Could not GET 'https://jitpack.io/com/github/thellmund/base/5.2.0/base-5.2.0.pom'. Received status code 401 from server: Unauthorized
```

**To Reproduce**
Implements newest version
Debug app

**Additional context**
 - WeekView version: 5.2.0

**Comment by OscarBeiro** [comment]
Same here

**Comment by Kaienu** [comment]
Hi,
I'm facing the same problem. Error 401 when implementing ver 5.2.0, 5.1.1 and 5.1.0. 
Initially, Gradle tells me everything is ok, but when android studio tries to build the apk the error raises.
![image](https://user-images.githubusercontent.com/34006136/100115552-f2d31000-2e72-11eb-97a2-5312ed0a6801.png)
Thanks for your time, you're doing a great job!

**Comment by thellmund** [comment]
Hi all 👋  I’ll take a look at this tonight. Sorry for the hassle!

**Comment by thellmund** [comment]
The issue is fixed. You can update to `5.2.1` and everything should be back to normal.

**Comment by Gnuhry** [comment]
It's working. Thanks :)
