### ISSUE TITLE
New Latest Release 5.2.1 displays only last event from the list 

### ISSUE THREAD

**Issue by imkhalid** [thellmund/Android-Week-View#206]
**Additional context**
 - Android version: [e.g. Android 10.0]
 - WeekView version: [5.2.1]

**Comment by thellmund** [comment]
Please provide more context and ideally a sample project that shows the issue.

**Comment by PedroTicGal** [comment]
Hi @imkhalid,
I was facing the same issue last week. I could see only the last event of a day.
The problem in my case was that all the events had the same internal id so they were been overridden by the last of the list.
Could this be the issue you are facing at?
Cheers!

**Comment by imkhalid** [comment]
> Hi @imkhalid,
> I was facing the same issue last week. I could see only the last event of a day.
> The problem in my case was that all the events had the same internal id so they were been overridden by the last of the list.
> Could this be the issue you are facing at?
> Cheers!

i was not using same id but i was generating random id, but after your suggestion i removed that part and created ids in incremental way and it worked.
