### ISSUE TITLE
submitList finishes but no Events on the screen

### ISSUE THREAD

**Issue by dsounded** [thellmund/Android-Week-View#209]
Thank you for the library!

**Describe the bug**

v.5.2.1
I'm trying to populate the events with the data from DB, I am using java8 simple adapter, the process goes pretty well but there is no result on the screen, not sure why...

**To Reproduce**
1) Use latest version
2) Use Java8 Simple provider
3) Populate the data
4) call **submitList**

**Expected behavior**
There are some results on the screen

**Screenshots**
https://prnt.sc/vu774b

**Additional context**
 - Android version: Android 8/11
 - WeekView version: 5.2.1

**Comment by dsounded** [comment]
I also tried Calendar version...same output

**Comment by thellmund** [comment]
Can you provide a sample repository that showcases the incorrect behavior?

**Comment by dsounded** [comment]
Holy crap I set start date same as end date, sorry for taking your time, closing this :(

**Comment by thellmund** [comment]
No worries! Let me know if anything else comes up 🙂
