### ISSUE TITLE
Strange behaviour on changing numberOfVisibleDays + scrollToDateTime

### ISSUE THREAD

**Issue by dsounded** [thellmund/Android-Week-View#211]
The flow is the following I am trying to implement switching between days and weeks (1 / 7 visible days, pretty popular goal I guess). The first problem it doesn't automatically go to the previous view day
e.g. I am on weeks: 2nd of December, scrolling to 9, changing state to day view, it becomes 3rd (like 1 page forward, instead of 7 in needed case) looks like there is no connection for curren tnumberOfVisibleDays  and needed amount of scrolling or something like that

Steps to reproduce described above, plus the second problem:

it doesn't work as expected with scrollToDateTime call. I guess the root of the problem is the same (it detects the number of page it needs to scroll for some cached numberOfVisibleDays result and uses same amount even after this value is changed)

**Expected behavior**
2nd December Week View(7 days)
Scroll one week forward -> 9th December
Change numberOfVisibleDays  to 1
Day view(1 day) is 9th December, now it's 3rd

**Additional context**
 - Android version: [e.g. Android 8-11]
 - WeekView version: [e.g. 5.2.1]

**Comment by dsounded** [comment]
+ strange thing for `onRangeChanged` listener in 7 days mode get invoked for each day (7 times) instead of 1 call per scroll

**Comment by dsounded** [comment]
In will be good to have an ability which will do instant goToDateTime.

without scrolling but rather re-rendering all the view

**Comment by dsounded** [comment]
Or... sort of `setMonthChangeListener` as we had in original repo, so this isn't triggered for each day but rather once per month/week/scroll. This will be really helpful

**Comment by dsounded** [comment]
@thellmund don't want to create another issue, can you please tell if there is an option to go to `defaultHour` on each page ?

not min/max but rather displaying all the hours but starting from 8AM (user can scroll to top to see 01AM for example) ?

Thank you for your time

**Comment by dsounded** [comment]
@thellmund have you had a chance to check this ?)

**Comment by thellmund** [comment]
👋 My notes:
1. Fixed in #215. Will try to get this out soon.
2. Nope, that seems to have been a bug. It’s fixed now in #215.
3. You can scroll to the desired hour with `weekView.scrollToTime(hour, minute)`.
