### ISSUE TITLE
Custom View for Entity

### ISSUE THREAD

**Issue by imkhalid** [thellmund/Android-Week-View#212]
**Is your feature suggestion related to a problem? Please describe.**
No

** Can you add Custom View or badge/tile for different category or user base**
![Capture](https://user-images.githubusercontent.com/40037273/101471317-fb464300-3968-11eb-860a-717ade5b3114.PNG)

while i am using this lib my client requirement was to show different color tile/badge for user role and different background color base on participant of event and i was able to show back color but i cant find a way to show badge or or bar in it.

**Comment by thellmund** [comment]
👋 Not entirely sure what you mean, even with the image you provided. Do you have a mock of what you want to display?
