### ISSUE TITLE
Static Week View doesn't scroll in a TabLayout with ViewPager2

### ISSUE THREAD

**Issue by iamarjun** [thellmund/Android-Week-View#214]
**Describe the bug**
I'm using the static week view in fragments with viewpager2, everything works fine on the first boot, even clicking the chevrons to go to next and the previous week works, the issue comes when visiting any of the tabs the second time, this time clicking the chevrons doesn't cause the view to scroll, I dig a little deep and found that `isWaitingToBeLaidOut` gets true and hence the code returns from the `scrollToDateWithCompletion` method.

this code block gets triggered when we visit any of the tabs the next time.

```
val isWaitingToBeLaidOut = ViewCompat.isLaidOut(this).not()
        if (isWaitingToBeLaidOut) {
            // If the view's dimensions have just changed or if it hasn't been laid out yet, we
            // postpone the action until onDraw() is called the next time.
            viewState.scrollToDate = adjustedDate
            return
        }
```

I have spun up a [demo app](https://github.com/iamarjun/WeekView) to reproduce the issue. 

**To Reproduce**
1. Go to the demo app and run it.
2. On the first launch check if the static scrolling works or not by clicking the left/right chevrons for all the tabs.
3. After visiting all the tabs again visit any of the previously visited tabs and now check if the scrolling works or not.

Ideally, the scrolling should work but it doesn't.

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.

**Additional context**
 - Android version: Android 11
 - WeekView version: 5.2.1

**Comment by thellmund** [comment]
👋 Thanks for providing a sample project. 

No immediate fix comes to mind. Here’s the implementation of `ViewCompat.isLaidOut()`: 
```kotlin
if (Build.VERSION.SDK_INT >= 19) {
  return view.isLaidOut();
}
return view.getWidth() > 0 && view.getHeight() > 0;
```

No idea why this defaults to `view.isLaidOut()` for API 19+, but simply using the width and height checks seems to work within `ViewPager2`. You can see yourself by adding these lines in `FragmentOne#onResume`:

```kotlin
val isLaidOutOld = binding.weekView.width > 0 && binding.weekView.height > 0
val isLaidOutNew = binding.weekView.isLaidOut()

Log.d("FragmentOne", "Old isLaidOut: $isLaidOutOld")
Log.d("FragmentOne", "New isLaidOut: $isLaidOutNew")
```

I might just change the code in WeekView to this then:
```kotlin
val isWaitingToBeLaidOut = width <= 0 || height <= 0
if (isWaitingToBeLaidOut) {
  // …
}
```

Let me have a closer look at this in the next few days. Will for sure include this in the next release, though.

**Comment by iamarjun** [comment]
Awesome, thanks I appreciate it.

**Comment by thellmund** [comment]
I went ahead and merged it. Will probably push out a new release in a few hours.

**Comment by thellmund** [comment]
Release is out!
