### ISSUE TITLE
Using with SQLite Room Library 

### ISSUE THREAD

**Issue by hasandeniz** [thellmund/Android-Week-View#217]
I want to use this library on my college homework and i am trying to learn how to use this library with SQLite Room library. Do i need to use and send to adapter class the viewModel like you did on example codes(creating on the activity page code) or my own viewModel that on my database class. Secondly i tried to use sample app link and it seems its not working.

**Comment by thellmund** [comment]
👋 Not sure that I understand what you mean. Can you elaborate?

Also, what do you mean by "sample app link"?
