### ISSUE TITLE
Background color for Event

### ISSUE THREAD

**Issue by RakeshPatil111** [thellmund/Android-Week-View#218]
I am following steps given at wiki page.
I want to add different background colors for events.
In sample code its not there.
How can I achieve this?
Thanks

**Comment by thellmund** [comment]
Hi 👋  

- If you want to set the standard background color for all events, you can use `defaultEventColor` (in XML) or `defaultEventColor` (in code).
- If you want to set a different color for each individual event, you need to use `WeekViewEntity.Style`. See [here](https://github.com/thellmund/Android-Week-View/blob/7197f70c3a25b87665878690e7f7e6a710e11282/sample/src/main/java/com/alamkanak/weekview/sample/ui/basic/BasicActivityWeekViewAdapter.kt#L39) for an example.

**Comment by RakeshPatil111** [comment]
Thank You So much

**Comment by RakeshPatil111** [comment]
Is it possible to change header height?
