### ISSUE TITLE
Events starting before minHour and ending after maxHour are not rendered

### ISSUE THREAD

**Issue by RemiNV** [thellmund/Android-Week-View#222]
**Describe the bug**
If an event starts before WeekView.minHour and ends after WeekView.maxHour, it is not rendered.

**To Reproduce**
1. Create a WeekView, set minHour to 7, maxHour to 21
2. Submit an event that starts at 5AM and ends at 10PM using a simple adapter

**Expected behavior**
The event is shown

**Actual behavior**
The event is not shown

This is due to SingleEventsUpdater#update, which checks event.isWithin(viewState.minHour, viewState.maxHour), and skips event chips that are not in the range.
It seems that there is an expectation that event chips are kept within minHour/maxHour, but WeekViewEntitiesSplitter does not always respect that: events are split with cut points on minHour / maxHour, but the original start/end dates can stay out of range. I have a change to update WeekViewEntitiesSplitter and will submit a PR.

**Comment by thellmund** [comment]
Nice! Will have a closer look in a bit.
