### ISSUE TITLE
Adding On Scroll listener when first visible date changed

### ISSUE THREAD

**Issue by Mohamadkotb** [thellmund/Android-Week-View#225]
I need to add a scrolling listener, so when the first visible date changed the callback triggered.

How can I clear the current events and add other events without trigger onLoadMore

**Comment by thellmund** [comment]
Please take a look at the wiki, which answers both of these questions.

**Comment by MohamedHarmoush** [comment]
I checked it before I created the question and checked it after you told me, but I couldn't find a setter method in WeekView to scroll listener when to be triggered after the user selects a date.

for more details

I want the calendar to show only one-day and fetch the events of the selected date and when the user scrolls calendar I want to fetch its events, so I set the visible days to be 1 and currently I want a scroll listener to be triggered when the user scrolled to next day or previous day.
I hope you're got my point.

And Thanks a lot for your great work.

**Comment by MohamedHarmoush** [comment]
@thellmund  Thanks I figure out that I was wrong.
the callback `fun onRangeChanged(firstVisibleDate: Calendar, lastVisibleDate: Calendar)`
is triggered after firstVisibleDate is changed.
Sorry for disturbing you and thanks for your help
