### ISSUE TITLE
Events not rendered

### ISSUE THREAD

**Issue by RakeshPatil111** [thellmund/Android-Week-View#226]
Sometimes event is not rendered.
This is my code
 val style = WeekViewEntity.Style.Builder()
                .setBackgroundColor(Color.parseColor(event.color))
                .build()

        val startTime = Calendar.getInstance()
        val endTime = Calendar.getInstance()

        startTime.time = event.startDate
        endTime.time = event.endDate

        val entity = WeekViewEntity.Event.Builder(event)
                .setId(event.id)
                .setTitle(event.title)
                .setStartTime(startTime)
                .setEndTime(endTime)
                .setStyle(style)
                .build()

        return entity

**Comment by thellmund** [comment]
Please provide a sample repo that showcases your issue. The snippet of code you posted doesn't really help in determining what is going wrong.

**Comment by RakeshPatil111** [comment]
Hi, I found debugged and find solution. Actually it was my mistake, events had an identical ids
