### ISSUE TITLE
Why not use java desugaring lib for using java8 date time on API < 26

### ISSUE THREAD

**Issue by iamarjun** [thellmund/Android-Week-View#228]

**Comment by alirazazoofy** [comment]
any work around for this. I am using api 21 in my project.

**Comment by iamarjun** [comment]
@alirazazoofy you can try my fork if you rely on java.time API for 21, basically what I did was I added desugarding to the `'com.github.thellmund.Android-Week-View:jsr310` enabling me to downgrade to 21 for my use case. @thellmund what do you think if my approach, is there a better way to do it, till now I don't seem to find any problems with my fork

**Comment by thellmund** [comment]
Hi @iamarjun ✌️ Looks like a solid idea to me, so I’m adding core-library desugaring in the `jsr310` module now.

**Comment by alirazazoofy** [comment]
thank you very much. @iamarjun  @thellmund
