### ISSUE TITLE
Unable to set dayBackgroundColor programmatically

### ISSUE THREAD

**Issue by frankwangyufei** [thellmund/Android-Week-View#232]
**Describe the bug**
Unable to set dayBackgroundColor programmatically

**To Reproduce**
1. Go to [BasicActivity](https://github.com/thellmund/Android-Week-View/blob/master/sample/src/main/java/com/alamkanak/weekview/sample/ui/basic/BasicActivity.kt)
2. Add `binding.weekView.dayBackgroundColor = Color.parseColor("#ff0000")` within `onCreate` (line 42, for example)
3. Install the sample app
4. Go to Basic view
5. The background color will not be changed (see screenshots)

**Expected behavior**
Background is set to red

**Screenshots**
![Current result](https://user-images.githubusercontent.com/28096697/108974201-33376980-76c0-11eb-8a6f-342e83b6f603.png)

**Additional context**
 - Android version: [Android 11.0]
 - WeekView version: [5.2.4]

**Comment by thellmund** [comment]
Thanks for reporting these issues. I addressed them in #234 and will release the next version today.
