### ISSUE TITLE
Trim text when it doesn't fit into the event card

### ISSUE THREAD

**Issue by PedroTicGal** [thellmund/Android-Week-View#238]
First of all, I would like to thank you for maintaining this great work. This is a great library but I find it odd when I want to visualize a very long text in the event surface (I'll call it "event card"). When this text is too long to display on that surface, the text just dissapears.

I think it would be great if the event card could measure how much text fits into its surface and trim the text finishing it with ellipsis if it doesn't fit.

I'm attaching a couple of screenshots to show this issue:

![Screenshot_1615214823](https://user-images.githubusercontent.com/48908942/110338556-6c100080-8027-11eb-9f9a-78e2f5a97ff5.png)
Here you can see the text of this event. It fits perfectly into the card.

![Screenshot_1615214845](https://user-images.githubusercontent.com/48908942/110338566-703c1e00-8027-11eb-9d81-9090d6a6a488.png)
As soons as I decrease the size of the card by zooming out the calendar, the text doesn't fit anymore and it vanish completely.

Thank you for all your hard work!

**Comment by thellmund** [comment]
👋 I added a fix for this. Will include it in the next release.
