### ISSUE TITLE
Drag n Drop Events

### ISSUE THREAD

**Issue by david-qualias** [thellmund/Android-Week-View#242]
It would be good to be able to drag and drop events. Also add handles on an event so the start and end time can be changed by dragging the handles on the event. This would take the library to the next level

**Comment by thellmund** [comment]
👋 Started working on this a bit today. Cross-day dragging is still buggy and I also need to make the view scroll once the user reaches the edges, but it’s coming along.

https://user-images.githubusercontent.com/11819826/117541965-82fdaf80-afe4-11eb-811e-203ebd50a05c.mov

**Comment by JSroka745** [comment]
Is this feature avalible in 5.3.2 version?
