### ISSUE TITLE
Wrong UI "showFirstDayOfWeekFirst"

### ISSUE THREAD

**Issue by HuuNguyen312** [thellmund/Android-Week-View#243]
**Describe the bug**
Normally, when set showFirstDayOfWeekFirst = true, the header will draw from Mon -> Sun
But the header draws incorrect after call week.scrollToDate

**Comment by thellmund** [comment]
Hi 👋 Can you elaborate on what exactly is drawn incorrectly? If possible, please provide a screenshot or screen recording of what the problem is.

**Comment by HuuNguyen312** [comment]
Normally, when set showFirstDayOfWeekFirst = true, the header will draw from Sun to Sat
After I click the today button (or call method week.scrollToDate), the header draws incorrect (from Thu to Web)
--> Expected Result: the header draws from Sun to Sat

https://user-images.githubusercontent.com/9895294/113957698-e6f85100-9849-11eb-9b60-6b55aa32d2a1.mp4

**Comment by thellmund** [comment]
Do you mean that the week view should stay in the Sunday-Saturday range when clicking the today button, instead of having Thursday as the first visible date?
