### ISSUE TITLE
Scroll Pager incorrect

### ISSUE THREAD

**Issue by HuuNguyen312** [thellmund/Android-Week-View#244]
**Describe the bug**
Scroll Pager incorrect

**Issue 1**
**To Reproduce**
1. Month type
2. I scroll a small distance
3. See error: WeekView only scroll to the next day

**Expected behavior**
Scroll to the next page

**Screenshots**

https://user-images.githubusercontent.com/9895294/113959210-a5b57080-984c-11eb-9e2e-883107259436.mp4

====================================

**Issue 2**
**To Reproduce**
1. Month type
2. I scroll page
3. When WeekView is fling, I click on any cell
4. See error: WeekView stop wrong page

**Expected behavior**
Scroll to the corect page

**Screenshots**

https://user-images.githubusercontent.com/9895294/113959727-94b92f00-984d-11eb-9485-ad92cac71e6e.mp4

**Comment by thellmund** [comment]
👋 Taking a stab at this in #246. Let me know what you think.
