### ISSUE TITLE
Zoom stopped working with version 5.3.0

### ISSUE THREAD

**Issue by FFSDevelopers** [thellmund/Android-Week-View#255]
**Describe the bug**
Zoom does not work when upgrading to version 5.3.0 .

**Comment by thellmund** [comment]
Works fine for me. Can you share a screen recording of your issue?

**Comment by FFSDevelopers** [comment]
It works fine in version 5.3.0 but the onDragAndDropFinished method is not available.

**Comment by FFSDevelopers** [comment]
> ~Works fine for me. Can you share a screen recording of your issue?~
> 
> Works fine in the 5.3.0 release, but it’s broken on `master`. If that’s what you meant, I just pushed a fix in [71d2472](https://github.com/thellmund/Android-Week-View/commit/71d2472d2ed0187f5dd60384a8461ac3e83629ed).

Perfect *__*
