### ISSUE TITLE
Recurring events

### ISSUE THREAD

**Issue by antoniokranjcina** [thellmund/Android-Week-View#256]
Hi,

is it possible to make an recurring event? For example event which happends every week on monday or every month on monday and sunday or somthing like that?

**Comment by thellmund** [comment]
Nope. You’ll have to do that yourself and submit the events to WeekView.

**Comment by rezazarchi** [comment]
Showing recurring events is possible. But you should know that every instance of a recurring event has the same ID. so you should create your own Id (for example, based on ID + start date in milliseconds) to show all of them without any conflicts. And also, you should have an exact ID in that object to work with the actual relevant event.
