### ISSUE TITLE
horizontalFlingEnabled does nothing

### ISSUE THREAD

**Issue by tylermarien** [thellmund/Android-Week-View#26]
Setting `horizontalFlingEnabled` to false has no effect. Regardless of what you set, you can still fling the view. My understanding is that this setting would prevent you from scrolling multiple screens at once, but still allow you to scroll on screen at a time.

**Comment by thellmund** [comment]
That also was my understanding when I started using the original library in another project. However, that was not the case. 

As mentioned in issue #4, I plan to integrate some sort of snappy scrolling at some point, where users can only scroll the same duration as is currently displayed on the screen (in week view, a user can scroll an entire week; in day view, a user can scroll only a day). I will likely use `horizontalFlingEnabled` to allow turning this on or off.
