### ISSUE TITLE
Show isAllDay event vertically (all hours)

### ISSUE THREAD

**Issue by ParitoshVaidya** [thellmund/Android-Week-View#262]
For all day event, the library is adding event at the top. I wanted to show it vertically (all hours). 

I set `isAllDay = true` and tried `arrangeAllDayEventsVertically` with no success.

Am I missing something?

**Comment by thellmund** [comment]
What do you mean by `I wanted to show it vertically (all hours)`? Do you want it to cover the entire day?

**Comment by ParitoshVaidya** [comment]
Yes. I wanted to cover entire day.

**Comment by thellmund** [comment]
If you don't want the event to appear at the top, set `isAllDay = false`. Then, set the `startTime` and the `endTime` to 0:00 and 23:59, respectively.

**Comment by ParitoshVaidya** [comment]
I did the same for time being. Thanks!
