### ISSUE TITLE
Event Time interval display error

### ISSUE THREAD

**Issue by kid3652** [thellmund/Android-Week-View#268]
**Describe the bug**
When I setStartTime16:40 and setEndTime 20:00，it just show like 16:40~19:45。(As shown below)

I still use weekView.setDateTimeInterpreter()，I am not sure if it make this bug.
( I use JAVA not Kotlin，I don't know how to use weekView.setDateFormatter() )

**Screenshots**
If applicable, add screenshots or a screen recording to help explain your problem.
![image](https://user-images.githubusercontent.com/57701043/140026658-aa940589-2cee-4d3f-9fa4-880f4d969dd1.png)

**Additional context**
 - Android version: 9.0
 - WeekView version:   5.3.2

**Comment by thellmund** [comment]
👋 Can you share a sample project where this problem occurs?

**Comment by kid3652** [comment]
> 👋 Can you share a sample project where this problem occurs?

Example Project: https://github.com/kid3652/WeekViewTest.git.

**Comment by thellmund** [comment]
[This](https://github.com/kid3652/WeekViewTest/blob/5d7a2d6e65d87723f34352e124fc0889f438338e/app/src/main/res/layout/activity_main.xml#L25) is the line that causes this: By setting `eventMarginVertical`, the event’s height will be reduced. I recommend to set this to `1dp` or `2dp`. This creates a visible separation between adjacent events, but doesn’t falsify their end dates as much.

**Comment by kid3652** [comment]
When I set eventMarginVertical , I didn't notice this situation. 
But it's well now.  Thank you very much.
