### ISSUE TITLE
Refresh and add events is rendered with as old events would exist 

### ISSUE THREAD

**Issue by thecodeside** [thellmund/Android-Week-View#275]
**Describe the bug**
When you refresh the adapter and load events it is rendered as old events would exist.
Screenshot before refresh and after refresh and resubmitted events attached.

**To Reproduce**
1. Submit Events 
2. Call refresh on the adapter
3. `loadMore()` is called
4. Events are submitted but rendered as old events would exist 

**Expected behavior**
Events rendered as it would be clear calendar instance.

**Screenshots**
Before refresh:
![1_before_refresh](https://user-images.githubusercontent.com/1507503/149956604-bf0fae43-717f-463d-9854-0658621a47ba.png)
After refresh and added events resubmited:
![2_after_refresh](https://user-images.githubusercontent.com/1507503/149956828-5026f43d-efea-4a97-9a78-dec76b0fbfcd.png)

**Additional context**
Latest sample app on the `master` branch.

**Comment by thellmund** [comment]
Hi there 👋 Where are you calling `refresh()` in the sample app?

**Comment by thecodeside** [comment]
I just added listener on click in the `BasicActivity` to test it. 
I can push changes if you want, but this is a very simple code.

```
    private lateinit var adapter: BasicActivityWeekViewAdapter
    
    override fun onCreate(savedInstanceState: Bundle?) {
      (...)
        adapter = BasicActivityWeekViewAdapter(
            dragHandler = viewModel::handleDrag,
            loadMoreHandler = viewModel::fetchEvents,
            onEmptyViewClick = {
                adapter.refresh()
            }
        )
        
        
private class BasicActivityWeekViewAdapter(
    private val dragHandler: (Long, LocalDateTime, LocalDateTime) -> Unit,
    private val loadMoreHandler: (List<YearMonth>) -> Unit,
    private val onEmptyViewClick: () -> Unit,
) : WeekViewPagingAdapterJsr310<CalendarEntity>() {  
        
       
    override fun onEmptyViewLongClick(time: LocalDateTime) {
        onEmptyViewClick()
        context.showToast("Empty view long-clicked at ${defaultDateTimeFormatter.format(time)}")
    }
```

**Comment by thellmund** [comment]
I see… the issue here is that `viewModel.fetchEvents()` never clears the already loaded events in the view state, therefore calling `refresh()` (which then calls `loadMore()`) will result in duplicate events. Can you try to update the view model’s `viewState` before calling `adapter.refresh()`?

**Comment by thecodeside** [comment]
You have 100% right! That fixes the bug! Thank you!
