### ISSUE TITLE
Is it possible to block scrolling to past dates?

### ISSUE THREAD

**Issue by Mauker1** [thellmund/Android-Week-View#32]
Say that I want to block the user for looking at past events, but I don't want to use the static view. Is it possible to block scrolling to a past time, but keep scrolling to a future one?

**Comment by thellmund** [comment]
Not at the moment. There are some other things I want to implement first, so this one will have to wait a bit. Of course, feel free to make a PR if you want 😊

**Comment by Mauker1** [comment]
Ok, thanks for the response. 

Which classes should I look at if I want to implement this behavior? How can I detect that the user is trying to scroll to a past date?

**Comment by cs8898** [comment]
Have a look at Quivr's fork they implemented such limit

**Comment by Mauker1** [comment]
Thanks for the information!

**Comment by cs8898** [comment]
I'm currently trying to implement that feature, if i got the Quivr Implementation right you have to modify the scroll events and block scrolling when the xOrigin would be beyond the allowed range... The Origin should be based on the currently displayed day (i assume this is DrawingContext.dayRange.get(0))
by calculating the difference to the minDate it should be possible to achieve that lock...

My current problem is finding the best way referencing the DrawingContext into the WeekViewGestureHandler...

**Comment by Mauker1** [comment]
I was also trying to implement the feature, but you're right, it's not that straightforward. Quivr's implementation still uses a "God class" to handle most of the view, it's way different from what we have here now.

**Comment by thellmund** [comment]
Implemented in 017ba70624040f50f092c9bc4e1362a60c217aa0.
