### ISSUE TITLE
Scroll detection not working correctly anymore

### ISSUE THREAD

**Issue by cs8898** [thellmund/Android-Week-View#38]
`config.drawingConfig.currentOrigin.x % config.totalDayWidth != 0f ` isn't correct anymore

One of both values gets wrong calculated

also the horizontal fling seems to missplace the entitys

**Comment by thellmund** [comment]
What exactly are you referring to? Please be more explicit of what you think is not working correctly.

**Comment by cs8898** [comment]
In `DrawingContext` there is the method `getVisibleDateRange`
```Kotlin
fun getVisibleDateRange(firstVisibleDate: Calendar, config: WeekViewConfig): List<Calendar> {
        val result = dateRange as MutableList
        val isScrolling = config.drawingConfig.currentOrigin.x % config.totalDayWidth != 0f
        if (isScrolling) {
            // If the user is scrolling, a new view becomes partially visible
            val lastVisibleDay = firstVisibleDate.clone() as Calendar
            lastVisibleDay.add(DATE, config.numberOfVisibleDays)
            dateRange.add(lastVisibleDay)
        }
        return result
    }
```

this is used to detect the presence of an AllDayChip in the header by adding the next day to the range if scrolling

I think this method should be removed and the handling should be done directly in the constructor.
While these values are currently not used correctly the dateRange holds too many Entrys, and the added last day is duplicated in the list...
my solution would be:
```Kotlin
@JvmStatic
        fun create(config: WeekViewConfig): DrawingContext {
            val drawConfig = config.drawingConfig
            val totalDayWidth = config.totalDayWidth
            val leftDaysWithGaps = (ceil((drawConfig.currentOrigin.x / totalDayWidth).toDouble()) * -1).toInt()
            val startPixel = (drawConfig.currentOrigin.x
                    + totalDayWidth * leftDaysWithGaps
                    + drawConfig.timeColumnWidth)

            val start = leftDaysWithGaps + 1
            var end = start + config.numberOfVisibleDays
            val modulo = config.drawingConfig.currentOrigin.x % config.totalDayWidth
            if (modulo == 0f) {
                end -= 1
            }
            val dayRange = DateUtils.getDateRange(start, end)

            return DrawingContext(dayRange, startPixel)
        }
```
This can be done, because the context is generated every time a draw is handled.

Currently the implementation seems working by resetting the header height at multiple positions.

the game changing Point is prepareDrawAllDayEvent(EventsDrawer.java) where you check isValidAllDayRect this will leave the chipHeight already set by prepareDrawAllDayEvents(EventsDrawer.java) at 0, while a valid rect wil overrite it to the correct height...

**Comment by thellmund** [comment]
You’re right. While the interface behaved like expected, the underlying calculations were wrong. I like your solution much better than my current one, as I have also not really been happy with `getVisibleDateRange()`. I’ve added it in fa75363e77a8b297d26f108c711c9a9c0a621fed.

**Comment by cs8898** [comment]
It still isn't correct...
only origin.x == 0 will set it to not scrolling
(Inset a Log command)

So the behavior is correct, but the behavior is determined by ``sValidAllDayRect` in `EventsDrawer.java`.

But the behavior should be consistent with the visibleRange and the Chips in that range...

**Comment by thellmund** [comment]
I’ve tested it via log statements and the date range switches between 3 and 4 dates depending on whether or not I am scrolling (with `numberOfVisibleDays` set to 3).

**Comment by thellmund** [comment]
I can’t reproduce what you’re saying: When using a 3-day view, the date range switches between 3 and 4 dates depending on whether or not I’m scrolling (as it should be). What would you change about this?

**Comment by cs8898** [comment]
Probably i'm completly wrong, but shouldn't the draw method be called on every move?
so on my phone in every frame i get a log output for `refreshHeaderHeight(HeaderRowDrawer.java)` there i will get constantly for all origin.x != 0 as last frame one date more than numOfVisibleDays

My Test: 
each move is flinging
numOfDays = 3
staring date = today()

Move -1 Day
LAST frame:  |mod| = 320.0
Move -1 Day
LAST frame:  |mod| = 319.666
Move +1 Day
LAST frame:  |mod| = 0.6666565 (viewable miss alignment of grid)
Move +1 Day (now i'm back at today()
LAST frame:  |mod| = 0.0
Move +1 Day
LAST frame:  |mod| = 0.6666565
Move +1 Day
LAST frame:  |mod| = 319.66666
Move +1 Day
LAST frame:  |mod| = 320.3333

My current idea
Flinging is accepting integer values, while the position and width are handled as float, could it be a rounding problem?

The TotalDayWidth is 320.33334 on my Screen (OnePlus 5T 1080 x 2160px)

**Comment by cs8898** [comment]
This is completely odd but i now know where the problem sits...

The Scroll Class only handles integer so while moveing the view gets snapped to the next available int
This snap can lead to an high enouth difference in the decimals that the modulo will be at 1 off
While this error grows to the future and to the past the modulo calculation gets worse and worser

I made a really dirty hack, and i think this calculation can be optimized much further i mad got the Modulo fluctuating between 0 and 1 at the edges for that i introduced a `SCROLL_THRESHOLD = 5` and my new calculation is:
```kotlin
val isNotScrolling = round(round(abs(drawConfig.currentOrigin.x)) % config.totalDayWidth) % round(config.totalDayWidth) <= Constants.SCROLL_THRESHOLD
```

At first i will calculate the offset by rounding the currentOrigin against the default width
The result can be some pixels off the originally wanted so i round that result and mod it with the rounded width
So i can get pretty close to the wanted snap point

But now i got a new error probably also occurring due to that floating bugs
```
2019-02-15 12:25:27.675 26092-26092/com.alamkanak.weekview D/ZOOMING: 15.08.2018 00:00:00 with Size: 3
2019-02-15 12:25:27.676 26092-26092/com.alamkanak.weekview D/ZOOMING: LAST 17.08.2018 00:00:00
2019-02-15 12:25:27.676 26092-26092/com.alamkanak.weekview D/ZOOMING: Orix 58622.0
2019-02-15 12:25:27.676 26092-26092/com.alamkanak.weekview D/ZOOMING: MOD  1
2019-02-15 12:25:27.676 26092-26092/com.alamkanak.weekview D/ZOOMING: WIDTH320.33334
```
So at Origin.x 58622.0 the date is 16.08.2018 but the first day is set to 15.08 leading to the drop of 18.08.2019

![screenshot_20190215-122745](https://user-images.githubusercontent.com/3143929/52853899-35ec4500-311d-11e9-9867-fd7bb55e9679.jpg)

**Comment by cs8898** [comment]
I created some new Calculation, that need optimization
It seems working, but there should be an better way of handling it than an loop...

The `i` will be the new leftDaysWithGaps value, it seems working for 2000 Days + and -
```Kotlin
//Calculating the Left Days by substracting as much as possible...
            var leftOrigin = drawConfig.currentOrigin.x
            var i = 0
            while(abs(leftOrigin) >= totalDayWidth) {
                if(leftOrigin > 0){
                    leftOrigin -= totalDayWidth
                    i--
                }else{
                    leftOrigin += totalDayWidth
                    i++
                }
            }
            //last rounding fix
            if(ceil((-1) * leftOrigin) >= floor(totalDayWidth))
                i++
            else if(round(leftOrigin) >= Constants.SCROLL_THRESHOLD) //round(totalDayWidth)
                i--
```
