### ISSUE TITLE
Show lines in the half hours and start/end hours

### ISSUE THREAD

**Issue by christian160984** [thellmund/Android-Week-View#39]
1 - Is possible to show lines in the half hours? 0:30, 1:30, 2:30...

2 - Is possible to define the start and end hours? 8am - 8pm

Thanks

**Comment by thellmund** [comment]
1. No, and not planned yet.
2. Not yet, but it’s planned. Hopefully, I’ll get to it sometime next month.

Feel free to make a pull request if you want contribute on these features.
