### ISSUE TITLE
Snap to first day of week

### ISSUE THREAD

**Issue by SapuSeven** [thellmund/Android-Week-View#4]
Hello,
is there some way I can get the WeekView to snap to the first day of the week when scrolling horizontally?
It should look like a paged view with one week per page.

**Comment by thellmund** [comment]
Not yet, but this is certainly something that I want to add in the near future.

**Comment by SapuSeven** [comment]
Any news on this? I could really use this feature...

**Comment by thellmund** [comment]
I did not yet find the time, but it’s definitely sometime that I want to do. I’ll update this issue when I start working on it.

**Comment by SapuSeven** [comment]
Thank you!

**Comment by marcelltoth** [comment]
I would also love to use that feature if you ever got the time to implement it. I would try a PR, but I am in a .NET (Xamarin Android) environment, I don't have neither the knowledge nor the toolset to work on Java / Kotlin
