### ISSUE TITLE
Custom font

### ISSUE THREAD

**Issue by christian160984** [thellmund/Android-Week-View#42]
Can I change the font of all the textviews?

**Comment by thellmund** [comment]
No, that’s currently not possible. I’ll keep it in mind as a new feature for a future version.

**Comment by thellmund** [comment]
I’ve started working on supporting custom fonts in the [`v4` branch](https://github.com/thellmund/Android-Week-View/tree/v4). You can find an example that uses a custom font family in the sample app (select _Custom Font_). Let me know if there’s anything missing.

**Comment by thellmund** [comment]
Closing this issue, as the feature is implemented and will be released with the next version. Feel free to re-open if there’s anything else regarding custom fonts.
