### ISSUE TITLE
notifyDataSetChanged() not working

### ISSUE THREAD

**Issue by christian160984** [thellmund/Android-Week-View#43]
I am trying to add an event programatically, but I dont get to refresh the calendar. This is my code:

override fun onMonthChange(startDate: Calendar, endDate: Calendar): List<WeekViewDisplayable<Event>> {

        events = mDatabase!!.getEventsInRange(startDate, endDate)
        return events!!
}

override fun onEmptyViewClicked(time: Calendar) {

       val hour = String.format(Locale.getDefault(), "%02d:%02d",
                                time.get(Calendar.HOUR_OF_DAY),
                                time.get(Calendar.MINUTE))

       val event = Event(System.currentTimeMillis(),
                        "Event: $hour",
                        time,
                        endTime,
                        "",
                        ContextCompat.getColor(context, R.color.colorPrimary),
                        false)

                events?.add(event)
                weekView?.notifyDataSetChanged()
}

**Comment by thellmund** [comment]
The issue is not in `notifyDataSetChanged()`, but in your `onMonthChange()`: Whenever this method is called, you query the events from the database. However, the event you create in `onEmptyViewClicked()` is never inserted into the database, as far as I can tell.

**Comment by christian160984** [comment]
Could you provide a code that adds an event?
