### ISSUE TITLE
set event background with border color

### ISSUE THREAD

**Issue by tdc-w** [thellmund/Android-Week-View#45]
I want to set a bordered background as the background of the event.
Is it possible to achieve it?
Background is white and border color is specified.

![image1](https://user-images.githubusercontent.com/38201241/55018749-d85de900-5036-11e9-9309-fd0f0b229ff5.png)

There was a similar issue.
https://github.com/alamkanak/Android-Week-View/issues/397

Thank you.

**Comment by thellmund** [comment]
That’s not currently possible, but I’m working on a way to allow this. Check out the latest commit on `develop` (it’s not finalized yet) and let me know what you think.

**Comment by tdc-w** [comment]
@thellmund 
Thank you for reply.
I have not tried, but if it can be realized in the way described in the issue, how about adopting it?
I want to specify in xml like `eventBackgroundBorder = true`.

**Comment by tdc-w** [comment]
Sorry, I overlooked WeekViewEvent.Style.
I feel that design can be realized using this.
