### ISSUE TITLE
Daylight saving time - bug, one hour is missing and one is duplicated

### ISSUE THREAD

**Issue by VEndymionV** [thellmund/Android-Week-View#46]
Hello!
Firstly, thank you @thellmund  for maintaining this library.

I found a bug connected with daylight saving time change.
31.03.2019 Poland changed time to DST (from 02:00 to 03:00) and I observed that time column contains two 03:00 hours. If system clock is set to 31.03.2019 all days have this bug:
![image](https://user-images.githubusercontent.com/29087969/55363193-8c9abc00-54dc-11e9-87c6-fff214f71b67.png)

I would be very grateful if you could fix it.

**Comment by thellmund** [comment]
Thanks for reporting. I’ll have a look at this soon.

**Comment by thellmund** [comment]
Fixed the bug in fbc0035a072ff6eac5a5b0a0bb4a4e1912599448. Not the nicest solution, but seems to work. Let me know if you notice any issues.

**Comment by VEndymionV** [comment]
Thanks for quick response. Yeah, the bug seems to be fixed but probably this fix makes another bug. Now the newLine is sticked to the top of the day, look at the screenshot:
![Screenshot (31 mar 2019 18_16_17)](https://user-images.githubusercontent.com/29087969/55444480-e4a5f100-55b6-11e9-981d-f01837e223f2.jpg)
I think that it is related to the fix that you made in latest commit but I can be wrong.

**Comment by thellmund** [comment]
You’re right, my bad. This is also fixed now.

**Comment by VEndymionV** [comment]
Great, thanks!
