### ISSUE TITLE
onMonthChange is called multiple times

### ISSUE THREAD

**Issue by tdc-w** [thellmund/Android-Week-View#47]
It is implemented referring to the sample AsyncActivity.

If you scroll to more than one month before and after the initial display month, onMonthChange is called multiple times, and the movement seems strange.
https://github.com/thellmund/Android-Week-View/blob/develop/sample/src/main/java/com/alamkanak/weekview/sample/AsyncActivity.kt#L101

Is there a bug in setMonthChangeListener?

**Comment by thellmund** [comment]
I’ll have a look at this in the next few days.

**Comment by thellmund** [comment]
Issue should be fixed. Check out f47ca9d1929e94f2398d47189ddf85ba90344bd2 and let me know if you notice anything weird.
