### ISSUE TITLE
Text color event

### ISSUE THREAD

**Issue by christian160984** [thellmund/Android-Week-View#48]
Hello, 

can each event have a different color? I have seen that it can in the develop branch. Can it be done in the master branch? If can not master, you can make a merge of the 2 branches and include this functionality? 

How can I include the develop branch in Gradle?

Thank you

**Comment by thellmund** [comment]
👉 [Release 3.2](https://github.com/thellmund/Android-Week-View/releases/tag/3.2)

**Comment by christian160984** [comment]
If I make this: weekViewEvent.setTextColor(int textColor), I change the color for all events. I want all events with white color and when I create a new event, I wanr this event with red color.

How do I do this?

**Comment by thellmund** [comment]
> If I make this: weekViewEvent.setTextColor(int textColor), I change the color for all events

No, it works on a per-event level.

**Comment by christian160984** [comment]
This is my code:

override fun onEmptyViewClicked(time: Calendar) {

                    weekView?.eventTextColor = ContextCompat.getColor(this, R.color.red)
                    events?.add(event)
                    weekView?.notifyDataSetChanged()
}

Initial event color text = white. Before = ALL events red
How can I get only the last event with red color?

**Comment by thellmund** [comment]
You’re calling `WeekView.setEventTextColor()`, not `WeekView*Event*.setTextColor()`. The former sets the default text color for all events. From my understanding, the latter is what you’re looking for.

**Comment by christian160984** [comment]
I'm implementing 'com.github.thellmund:Android-Week-View:3.3'. This version doesn't have WeekViewEvent.setTextColor()

![Sin título](https://user-images.githubusercontent.com/7393899/55783033-d3c11800-5aad-11e9-8220-eb747df333d6.png)

**Comment by thellmund** [comment]
You’re calling the method on `WeekView`, but you must call it on the `WeekViewEvent` whose color you want to change.

**Comment by christian160984** [comment]
This is my code. This not working. Which is my error?

`class Event(
        val id: Long,
        val title: String,
        val startTime: Calendar,
        val endTime: Calendar,
        val color: Int,
        val status: BookingStatusType?
) : WeekViewDisplayable<Event> {

    override fun toWeekViewEvent(): WeekViewEvent<Event> {
        return WeekViewEvent(id, title, startTime, endTime, "", color, false, this)
    }
}`

`event.toWeekViewEvent().textColor` = ContextCompat.getColor(this, R.color.red)
`events?.add(event)`
`weekView?.notifyDataSetChanged()`

**Comment by thellmund** [comment]
You will need to set the text color in `toWeekViewEvent()`. Something like this:

```kotlin
override fun toWeekViewEvent(): WeekViewEvent<Event> {
    return WeekViewEvent(id, title, startTime, endTime, "", color, false, this).apply {
        textColor = // ...
    }
}
```

**Comment by christian160984** [comment]
Many thanks! Your code works fine!
