### ISSUE TITLE
unresolved referenceBuilder

### ISSUE THREAD

**Issue by qiubochen** [thellmund/Android-Week-View#49]

**Comment by qiubochen** [comment]
我复制你的sample里面的Event，但是里面代码提示unresolved reference：Builder，本人kt并不熟练所以想请问这个是什么原因，代码如下
'''
import android.graphics.Color
import com.alamkanak.weekview.WeekViewDisplayable
import com.alamkanak.weekview.WeekViewEvent
import java.util.*
class WeekEvent(
        val id: Long,
        val title: String,
        val startTime: Calendar,
        val endTime: Calendar,
        val location: String,
        val color: Int,
        val isAllDay: Boolean,
        val isCanceled: Boolean
): WeekViewDisplayable<WeekEvent> {

    override fun toWeekViewEvent(): WeekViewEvent<WeekEvent> {
        val backgroundColor = if (!isCanceled) color else Color.WHITE
        val textColor = if (!isCanceled) Color.WHITE else color
        val borderWidth = if (!isCanceled) 0 else 4

        val style = WeekViewEvent.Style.Builder()
                .setTextColor(textColor)
                .setBackgroundColor(backgroundColor)
                .setTextStrikeThrough(isCanceled)
                .setBorderWidth(borderWidth)
                .setBorderColor(color)
                .build()

        return WeekViewEvent.Builder<WeekEvent>()
                .setId(id)
                .setTitle(title)
                .setStartTime(startTime)
                .setEndTime(endTime)
                .setLocation(location)
                .setAllDay(isAllDay)
                .setStyle(style)
                .setData(this)
                .build()
    }

}
'''

**Comment by cs8898** [comment]
The hack... I dont understand anything here... Just something unreferenced called Builder, could be the subclass in WeekViewEvent

Probably just do a rebuild and re index...

**Comment by thellmund** [comment]
@qiubochen Please post your questions in English.

**Comment by qiubochen** [comment]
i‘m sorry。i have solved  my question.but i have another question.i will post my question in English
