### ISSUE TITLE
Android-Week-View in fragment

### ISSUE THREAD

**Issue by qiubochen** [thellmund/Android-Week-View#50]
i use Android-Week-View in fragment. when Android-Week-View is initialized, setMonthChangeListener() is called three times。here is my code.
`@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {
        // Inflate the layout for this fragment

        View view=inflater.inflate(R.layout.fragment_data, container, false);
        weekView=view.findViewById(R.id.weekView);
        if (weekView!=null){
            weekView.setMonthChangeListener(new MonthChangeListener<CalendarItem>() {
                @NotNull
                @Override
                public List<WeekViewDisplayable<CalendarItem>> onMonthChange(Calendar calendar, Calendar calendar1) {
                  return DataUtil.getDataList();
                }

            });

        }

        System.out.println("+++++++++++++");
        weekView.setMinDate(DateUtil.getNowDate());
        System.out.println(DateUtil.getNowDate().getTime());
        weekView.setMaxDate(DateUtil.getAfterDate(5));
        System.out.println(DateUtil.getAfterDate(5).getTime());
        weekView.setEventTextColor(Color.BLACK);
        return view;
    }`

**Comment by qiubochen** [comment]
This is the result
![微信图片编辑_20190409154102](https://user-images.githubusercontent.com/25119414/55782005-fc610600-5add-11e9-89ba-c948751dc691.jpg)

**Comment by thellmund** [comment]
`onMonthChange` is called three times – once for the current month, once for the previous month and once for the next month. You need to filter the results coming from your `DataUtil.getDataList()` for items that are between `startDate` and `endDate`.
