### ISSUE TITLE
Scroll listener

### ISSUE THREAD

**Issue by christian160984** [thellmund/Android-Week-View#53]
It's possible detect when Weekview is scrolling and when the scroll has finished?

I want load the events when the day changes. And I want prevent multiple calls with fast scroll

**Comment by christian160984** [comment]
It's possible prevent fast scroll?

**Comment by christian160984** [comment]
It's possible prevent fast scroll?

**Comment by thellmund** [comment]
No, not at the moment. It’s something that is planned, though (see #4).

**Comment by christian160984** [comment]
Limit the scroll to 1 day, 3 days, 7 days ... and not to infinite scroll, it is a very important improvement for the calendar. I would be very grateful if you make this improvement
