### ISSUE TITLE
notifyDataSetChanged() isn't working on latest version

### ISSUE THREAD

**Issue by VEndymionV** [thellmund/Android-Week-View#55]
I was thinking that `notifyDataSetChanged()` notify `WeekView` that it should invoke `onMonthChange` method but... no. I'm updating my events List and calling `notifyDataSetChanged()` but it does nothing, `onMonthChange()` which should load events isn't called. Should I invoke `onMonthChange()` manually when I want to update events?
**This method is working fine on last release version but not in latest commit(s).**

**Comment by cs8898** [comment]
Try to do a ```invalidate()``` on the view after, that should trogger a reload in the next render cycle

I thinkt thats what i always did...

**Comment by VEndymionV** [comment]
@cs8898 Yes, unfortunately `invalidate()` didn't help with that but thanks for trying :+1:

**Comment by cs8898** [comment]
But you called it from the UI thread?
FAIK you are only alowed to call that method from the UI thread probably a cal from an other thread is dropped (but there should be an ErrorLog in such case)

**Comment by VEndymionV** [comment]
I called it in my Fragment `getView()?.invalidate()` and also I try to call it on `WeekView` object.
**I noticed something important now:**
When I roll-back to last release `notifyDataSetChanged()` is working! @thellmund You probably breaked something by mistake in latest commits.

**Comment by thellmund** [comment]
The functionality broke in a recent refactoring. I’ve fixed it on `master` now (5315c2d723984016279d707ab78c2e489d853e77).
