### ISSUE TITLE
Updating the latest code on Jitpack

### ISSUE THREAD

**Issue by jenishStudent** [thellmund/Android-Week-View#56]
Could you update the notifyDataSetChanged on your jitpack so I can continue to use your library. Thank You, really love what you have done with the library.

**Comment by VEndymionV** [comment]
You can select specific commit on JitPack and use it. https://jitpack.io/#thellmund/Android-Week-View
Click arrow, then select "develop", and then click "Commits".

**Comment by thellmund** [comment]
I’ll try to have a new version out sometime next week. In the meantime, you can follow @VEndymionV‘s suggestion to get the newest features.
