### ISSUE TITLE
Empty space with columnGap

### ISSUE THREAD

**Issue by christian160984** [thellmund/Android-Week-View#58]
If calendar has column gap value, the empty space is not visible in last day.
![Screenshot_20190508-093700](https://user-images.githubusercontent.com/7393899/57358660-36253b00-7176-11e9-99d4-0aa46196cf91.png)
Is this a bug or can empty space be displayed?

**Comment by christian160984** [comment]
<com.alamkanak.weekview.WeekView
                android:id="@+id/weekView"
                android:layout_width="match_parent"
                android:layout_height="match_parent"
                app:horizontalScrollingEnabled="true"
                app:columnGap="50dp"
                app:eventCornerRadius="3dp"
                app:eventPadding="10dp"
                app:eventTextColor="@android:color/white"
                app:eventTextSize="10sp"
                app:firstDayOfWeek="monday"
                app:headerRowBottomLineColor="@color/line_separator"
                app:headerRowBottomLineWidth="1dp"
                app:headerRowPadding="10dp"
                app:headerRowTextColor="@color/black"
                app:headerRowTextSize="15sp"
                app:hourHeight="52dp"
                app:nowLineColor="@color/red"
                app:nowLineDotColor="@color/red"
                app:nowLineDotRadius="9dp"
                app:nowLineStrokeWidth="1dp"
                app:numberOfVisibleDays="1"
                app:showFirstDayOfWeekFirst="true"
                app:showHeaderRowBottomLine="true"
                app:showNowLine="true"
                app:showNowLineDot="true"
                app:showTimeColumnSeparator="true"
                app:singleDayHorizontalMargin="0dp"
                app:singleLineHeader="false"
                app:timeColumnBackgroundColor="@android:color/white"
                app:timeColumnPadding="20dp"
                app:timeColumnSeparatorColor="@color/line_separator"
                app:timeColumnSeparatorStrokeWidth="1dp"
                app:timeColumnTextSize="12sp"
                app:todayHeaderTextColor="@color/colorPrimary"
                app:horizontalFlingEnabled="false"/>

**Comment by thellmund** [comment]
Will address this with the next version. Thanks for reporting.

**Comment by thellmund** [comment]
I pushed a fix with 35e5645315570139a4b1fa6cf6972804ce1572f5. Let me know if there’s anything else.
