### ISSUE TITLE
Not showing 4 allDay events with columnGap value

### ISSUE THREAD

**Issue by christian160984** [thellmund/Android-Week-View#59]
If columnGap has value and I have 4 o more allDay events, no event is shown below the day.

Also, if columngap has value, a space to the right of allDay events and below the date is shown.

**Comment by thellmund** [comment]
Please add a screenshot to this issue.

**Comment by christian160984** [comment]
![1](https://user-images.githubusercontent.com/7393899/57368914-9cb55380-718c-11e9-9dea-bf1b9b35ec67.png)
![2](https://user-images.githubusercontent.com/7393899/57368918-9f17ad80-718c-11e9-9aa2-68274be5cc13.png)

**Comment by thellmund** [comment]
I have not been able to reproduce this issue (I used `columnGap`, two-line headers, etc). Could you prepare a [SSCCE](http://sscce.org/)?
