### ISSUE TITLE
Color of WeekView event

### ISSUE THREAD

**Issue by Kotvitz** [thellmund/Android-Week-View#61]
Do you know how to set the color of a single event (rectangle in the timeline) on the XML side? It is possible to implement this on the Kotlin side, but I would rather do it on the XML layout side. I think that may be 'defaultEventColor', but it doesn't work.

**Comment by thellmund** [comment]
There was an error in the `WeekViewEvent` class. I’ve pushed a fix to the `develop` branch which you can check out and will push a new version soon.
