### ISSUE TITLE
Saved instance state overwrites layout parameters on config change

### ISSUE THREAD

**Issue by jcogilvie** [thellmund/Android-Week-View#62]
When I have a layout file with `app:numberOfVisibleDays="1"` for portrait and a second file with `app:numberOfVisibleDays="7"` for landscape, when I switch orientations on my device, the actual number of visible days remains whatever it was to begin with.  Expected behavior is that for a given configuration, the xml is always used if it exists.

Stepping through the debugger it appears that the saved instance state is overwriting the value passed from xml.

**Comment by jcogilvie** [comment]
Seems to be new in this commit.  https://github.com/thellmund/Android-Week-View/commit/b3e4eaf7b9ee01f99f8a5aa52000a5ac59abe94e#diff-c8d5abb0096668b146d387875cbaa7af

**Comment by thellmund** [comment]
Thanks for bringing this to my attention. My initial idea was that if the user switched the number of days (e.g. via the overflow menu in the sample app), they would want the number of days to stay the same on device rotation. I didn’t consider the case where you’d have two different layout files, though.

I’ve looked at your pull request and appreciate your effort, but I think the problem should be solved in a different way. I’ve pushed a commit just now (f375a2bbc8c780ecf6e96db2817161d6e9ec7dc1) where you can opt out of remembering the number of days, which should address your issue. 

Let me know if it works and if there’s anything else.
