### ISSUE TITLE
RTL support

### ISSUE THREAD

**Issue by jcogilvie** [thellmund/Android-Week-View#65]
Thanks for being responsive on my other issues.

I'm trying to use this in a big corporate app that'll require RTL support.  I'm not an expert on RTL for calendars, but I'm thinking that it should obey the system's locale in that regard in two specific ways that are immediately visible.

First, in an RTL locale I'd expect the time label column to show up at the `start` of the layout (so the right).  Second, I'd expect the individual events' labels to appear start-aligned.

I'm not sure if RTL should mess with the directionality of the dates on scrolling... but something else to think about.

**Comment by tlozovyi** [comment]
As far as I know in RTL scrolling should be also reversed - next days should be to the left. So if used to show more than 1 day on screen - most recent date should be on the left.

**Comment by thellmund** [comment]
Hi @jcogilvie, it’s a great suggestion and I really want to support it. I’m not sure when I’ll get around to it, but I’ll keep you updated.

**Comment by thellmund** [comment]
It only took me one and a half years, but I’m finally working on it: #168. If it’s still interesting to you, I’d love your feedback on it.

**Comment by thellmund** [comment]
Merged into `master`. Will release it with beta 4 right now.

**Comment by tlozovyi** [comment]
Thanks for the great update!
I've recently updated to most recent version (5.0.3) and it works like a charm!
