### ISSUE TITLE
Restoring instance state causes NPE

### ISSUE THREAD

**Issue by jcogilvie** [thellmund/Android-Week-View#66]
I have an activity (containing the week view) that quickly checks for authentication, and, if unauthenticated, pops another activity over the current one.

When the new activity pops and then closes, the calendar is put through a very quick save/restore state cycle *before* the `viewState` is completely initialized (i.e. before `firstVisibleDay` is set to anything).  

`onRestoreInstanceState` needs to handle the case of a null `firstVisibleDay`.  Other methods safely handle the null case for this property, which makes me think this was just a small oversight.

Presently, in this case, `toCalendar` throws a kotlin NPE.  Using v3.4.2.

**Comment by thellmund** [comment]
I made `firstVisibleDay` nullable in f252f5c1f5ee9c600447e1b50fb67a096a209631. Let me know if that addresses your issue.
