### ISSUE TITLE
WeekView can't be rendered.

### ISSUE THREAD

**Issue by SE7-KN8** [thellmund/Android-Week-View#68]
Currently, when including the WeekView in a layout, it can not be rendered by AndroidStudio (in the layout preview) and throws a `ClassNotFoundException`. This is because it uses classes from `com.jakewharton.threetenabp`. To make these classes available for the layout preview, it would help to change the type of this dependency from `implementation` to `api`, but I don't know if it's the best way.

**Comment by thellmund** [comment]
You’re right, I didn’t think about that when I started to use this library. However, I no longer think it’s a good idea to include a third-party library if avoidable, so I spent some time today getting rid of it again (along with refactoring other parts of the app; see the [`v4` branch](https://github.com/thellmund/Android-Week-View/tree/v4)). That solves the preview issue, so I’ll close this issue now. The fix will be part of the next release.
