### ISSUE TITLE
Horizontally scrolling to next day initially shows blank page

### ISSUE THREAD

**Issue by Menthuss** [thellmund/Android-Week-View#7]
I've noticed that this fork has an issue with showing the next page while scrolling to the next day. Having set the amount of visible days to 1, when I scroll to the next day, the next day page remains blank until scrolling has finished. I'm guessing this is happening because the next page isn't loaded in advance?

**Comment by SapuSeven** [comment]
You are right, this is even an issue in the sample app. I will look into this.

**Comment by thellmund** [comment]
Hi @Menthuss, not sure how I missed this 🤔 It’s fixed now in the `develop` branch. Let me know if there are any other problems.
