### ISSUE TITLE
Allow use of @ColorRes for style colors

### ISSUE THREAD

**Issue by jcogilvie** [thellmund/Android-Week-View#70]
Presently the API for setting colors in the style builder requires @ColorInt integers.  It would be helpful if I could provide @ColorRes ints and allow the WeekView to look up the colors using its own Context.  (This saves me from storing a context reference in my WeekViewEvent subclass.)

**Comment by thellmund** [comment]
Agreed. I had planned this for some time, but didn’t get around to it. But given my current [refactoring for v4](https://github.com/thellmund/Android-Week-View/tree/v4), I have pushed a first implementation. I’ll polish it some more before the release, but you can already try it out.

**Comment by jcogilvie** [comment]
While we're at it, setTitle and setLocation might be overloaded to take @StringRes too.

**Comment by jcogilvie** [comment]
One thing you might want to note in your refactor.  I see [here](https://github.com/thellmund/Android-Week-View/blob/v4/library/src/main/java/com/alamkanak/weekview/WeekViewEvent.kt) that your Style builder is using `var`s set on a `private Style`.  Consider using `var`s only in your builder, and constructing a `Style` in `build()` using named parameters, so that they can be `val`s in the final object.  That's one of the underlying motivations of the builder pattern.

**Comment by thellmund** [comment]
Using color and string resources is now in the `develop` branch and will be included in the next release. Closing this issue now, but feel free to re-open if you discover any issues.
