### ISSUE TITLE
 EventClickListener is not respond

### ISSUE THREAD

**Issue by zj2050** [thellmund/Android-Week-View#72]
language is java not kotlin

` mWeekView.setOnEventClickListener(new EventClickListener () {
            @Override
            public void onEventClick(Object o, RectF rectF) {

                Toast.makeText(mContext,"hi",Toast.LENGTH_LONG).show();

            }
        });`

then touched event the app will crashed

D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zhixin, PID: 27016
    java.lang.IllegalStateException: No data to show. Did you pass the original object into the constructor of WeekViewEvent?
        at com.alamkanak.weekview.Preconditions.checkState(Preconditions.kt:17)
        at com.alamkanak.weekview.WeekViewGestureHandler.onSingleTapConfirmed(WeekViewGestureHandler.java:242)
        at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:312)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6944)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
E/CrashReport: Java Crash Happen cause by main(2)
I/CrashReport: user log size:0
E/CrashReport: stack frame :9, has cause false

thanks

**Comment by zj2050** [comment]
`            WeekViewEvent event = new WeekViewEvent(idset++, Title, startCal, endCal);
            //event.setLocation(Location);
            event.setColor(Colour);`

**Comment by thellmund** [comment]
The error includes the hint: `No data to show. Did you pass the original object into the constructor of WeekViewEvent?`

`WeekView` is generic, so you should pass it the type of object that you want to get back in `onEventClick()` (the class that implements `WeekViewDisplayable`). Take a look at [`BaseActivity`](https://github.com/thellmund/Android-Week-View/blob/develop/sample/src/main/java/com/alamkanak/weekview/sample/BaseActivity.java) and [`Event`](https://github.com/thellmund/Android-Week-View/blob/develop/sample/src/main/java/com/alamkanak/weekview/sample/apiclient/Event.kt) from the sample.

**Comment by zj2050** [comment]
> The error includes the hint: `No data to show. Did you pass the original object into the constructor of WeekViewEvent?`
> 
> `WeekView` is generic, so you should pass it the type of object that you want to get back in `onEventClick()` (the class that implements `WeekViewDisplayable`). Take a look at [`BaseActivity`](https://github.com/thellmund/Android-Week-View/blob/develop/sample/src/main/java/com/alamkanak/weekview/sample/BaseActivity.java) and [`Event`](https://github.com/thellmund/Android-Week-View/blob/develop/sample/src/main/java/com/alamkanak/weekview/sample/apiclient/Event.kt) from the sample.

thanks
