### ISSUE TITLE
The content height of weekview affects other weekview

### ISSUE THREAD

**Issue by tdc-w** [thellmund/Android-Week-View#73]
I develop the following screen.

![スクリーンショット 2019-06-13 1 31 20](https://user-images.githubusercontent.com/38201241/59369929-7468d800-8d7c-11e9-84fd-2ead960840f5.png)

Each xml defines weekview, and activity shows custom view(status message view).
As you can see, when back to fragment from activity, the height of weekview will shrink by the height of custom view.
It looks like a content height, not the height of the view itself.

![スクリーンショット 2019-06-13 1 55 29](https://user-images.githubusercontent.com/38201241/59370943-a11def00-8d7e-11e9-8c3e-709d1efc56ab.png)

After scrolling down, tapping on space crashes.

```
Process: com.sample.weekview, PID: 6794
    org.threeten.bp.DateTimeException: Invalid value for HourOfDay (valid values 0 - 23): 24
        at org.threeten.bp.temporal.ValueRange.checkValidValue(ValueRange.java:278)
        at org.threeten.bp.temporal.ChronoField.checkValidValue(ChronoField.java:557)
        at org.threeten.bp.LocalTime.withHour(LocalTime.java:833)
        at org.threeten.bp.LocalDateTime.withHour(LocalDateTime.java:927)
        at org.threeten.bp.ZonedDateTime.withHour(ZonedDateTime.java:1309)
        at com.alamkanak.weekview.WeekViewTouchHandler.getTimeFromPoint(WeekViewTouchHandler.kt:50)
        at com.alamkanak.weekview.WeekViewGestureHandler.onSingleTapConfirmed(WeekViewGestureHandler.java:253)
        at android.view.GestureDetector$GestureHandler.handleMessage(GestureDetector.java:300)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:241)
        at android.app.ActivityThread.main(ActivityThread.java:6217)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
```

weekview in xml
```
<com.alamkanak.weekview.WeekView
        android:id="@+id/weekView"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        app:columnGap="1dp"
        app:eventCornerRadius="4dp"
        app:eventPadding="4dp"
        app:eventTextColor="@color/white"
        app:headerRowBottomLineColor="@color/mainGray"
        app:headerRowBottomLineWidth="1dp"
        app:headerRowPadding="12dp"
        app:hourHeight="60dp"
        app:nowLineColor="@color/mainPurple"
        app:nowLineDotColor="@color/mainPurple"
        app:nowLineDotRadius="5dp"
        app:nowLineStrokeWidth="1dp"
        app:numberOfVisibleDays="3"
        app:overlappingEventGap="1dp"
        app:showCurrentTimeFirst="true"
        app:showHeaderRowBottomLine="true"
        app:showNowLine="true"
        app:showNowLineDot="true"
        app:showTimeColumnSeparator="true"
        app:singleDayHorizontalMargin="8dp"
        app:singleLineHeader="false"
        app:timeColumnBackgroundColor="@color/white"
        app:timeColumnPadding="8dp"
        app:timeColumnSeparatorColor="@color/mainGray"
        app:timeColumnSeparatorStrokeWidth="1dp"
        app:timeColumnTextColor="@color/mainBlack"
        app:timeColumnTextSize="12sp"
        app:todayHeaderTextColor="@color/mainGreen"
        app:todayBackgroundColor="@color/todayBackground"
        app:maxHourHeight="60dp"
        app:minHourHeight="60dp"
        />
```

Do you know the cause?
Thanks.

**Comment by thellmund** [comment]
I have a suspicion of what might be the issue and will incorporate a fix in the next version.

**Comment by tdc-w** [comment]
Thanks.
There may be a problem with the layout, so I will investigate the cause here.

**Comment by thellmund** [comment]
I believe that 86009e4acc7685dc896010d477821c3dc57f5f8a fixes your issue. If you’re brave enough, you can try it out on the current develop snapshot – there are some breaking changes when upgrading from v3.4.2, though. 

I’ll close this issue now. If you continue to experience issues, feel free to re-open it.

**Comment by tdc-w** [comment]
@thellmund 
Hi.
I plan to implement the above screens by the end of this month.
When is the next release (3.4.3?) Including this fix planned?

**Comment by thellmund** [comment]
The next version will be 4.0.0, and I plan on finishing it mid-August. Until then, you should be able to force a size refresh of WeekView via `weekView.requestLayout()` as temporary workaround.

**Comment by tdc-w** [comment]
Thanks.
I tried to call weekView.requestLayout() in onResume, but it was not improved.
Do you have any other ideas?

**Comment by tdc-w** [comment]
As I use fragment, it seems to be improved by removing and adding fragment.
I think that there is no problem as a temporary workaround.
Thanks.
