### ISSUE TITLE
refresh weekView after delete an event

### ISSUE THREAD

**Issue by MohammadB72** [thellmund/Android-Week-View#74]
i have problem after deleting event from events and call weekView.notifyDataSetChanged()
here is my code 👇

`private fun onEventClick(event: ApiEvent, eventRect: RectF)`
`{`
`        this.events.remove(event)`
`        weekView.notifyDataSetChanged()`
`}`

my problem is : deleted event stay in the weekView and don't be clear

**Comment by thellmund** [comment]
How does your `onMonthChange()` look like?

**Comment by MohammadB72** [comment]
`private fun onMonthChange(startDate: Calendar, endDate: Calendar):List<WeekViewDisplayable<ApiEvent>>`
`{`
`        val newYear = startDate.get(Calendar.YEAR)`
`        val newMonth = startDate.get(Calendar.MONTH)`
`        return events.filter { eventMatches(it.toWeekViewEvent(), newYear, newMonth) }`
`}`

**Comment by thellmund** [comment]
You’re right. There was an issue where I didn’t clear the cached events. That’s why the event didn’t disappear. I fixed the issue on `develop` and will include the fix in the next version.
