### ISSUE TITLE
It is possible to set start calendar and end calendar?

### ISSUE THREAD

**Issue by biancaarno8** [thellmund/Android-Week-View#77]

**Comment by thellmund** [comment]
Yes. Take a look at `setMinDate()` and `setMaxDate()` in [https://github.com/thellmund/Android-Week-View/wiki/Public-Methods](the wiki).

**Comment by biancaarno8** [comment]
@thellmund thank you for the answer!
I want also to report a bug: i  I entered "startActivityForResult" into onEmptyViewClicked and onEventClicked, to add new events: when i finished to add event (in the new activit)  and set backintent and call finish, then  "onActivityResult"  doesn't trigger.
I hope I explained myself well.

**Comment by thellmund** [comment]
This doesn’t sound like an issue in the library to me.
