### ISSUE TITLE
Api 21 Issue

### ISSUE THREAD

**Issue by jenishStudent** [thellmund/Android-Week-View#79]
this library is not compiling in api 21 with your new changes

**Comment by thellmund** [comment]
Works just fine for me on an emulator with API 21. Can provide more info (e.g. console output) about what’s not working for you?

**Comment by jenishStudent** [comment]
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.hellmund.weekview_jsr310"
    android:versionCode="1"
    android:versionName="1.0" >

    <uses-sdk
        android:minSdkVersion="26"
        android:targetSdkVersion="29" />

</manifest>

**Comment by jenishStudent** [comment]
u have minsdkversion 26 in this

**Comment by jenishStudent** [comment]
in ur gradle u have set min sdk to 26, so if i use it with my min sdk being 21 doesnt work

**Comment by jenishStudent** [comment]
jsr310

**Comment by thellmund** [comment]
The `JSR310` module is intended for use with Java 8’s Date API, which is only available on API 26+. All other modules (including the core library) are available on API 21+.
