### ISSUE TITLE
Lower Api

### ISSUE THREAD

**Issue by jenishStudent** [thellmund/Android-Week-View#80]
If my app minimum api is less than 26 how can i import your library? which has api 26 for jsr...?

**Comment by thellmund** [comment]
For the current version, you need: 
`implementation 'com.github.thellmund:Android-Week-View:3.4.2'`

Once version 4 is released, it will be 
`implementation 'com.github.thellmund.Android-Week-View:core:4.0.0'`. 

You can try the latest commit from `master` via `implementation 'com.github.thellmund.Android-Week-View:core:develop-SNAPSHOT'`. However, it’s not an official release, so no guarantees.

**Comment by jenishStudent** [comment]
the implementation for new wont work since it doesnt support api lower then 26

**Comment by thellmund** [comment]
I don’t understand what you mean by that. 

All modules except `JSR310` have a minimum SDK of 21, so you can use them without issue. `JSR310` has a minimum SDK of 26, because Java 8’s Date API (for which the `JSR310` module is intended) also requires API 26+.

**Comment by jenishStudent** [comment]
Hi, when do you plan to have 4.0.0 out?

**Comment by thellmund** [comment]
I plan on finishing it mid-August.
