### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by christian160984** [thellmund/Android-Week-View#82]
Make **nowLineColor** reach the end if **columnGap** has value

Make **columnGap** not for all events and if for each individual event. It is possible to want some events if reach the end and others not

**Comment by thellmund** [comment]
I implemented your first suggestion on `develop` (commit 50fd190633c40451873b6b40b9d3e2bc4cba330e). However, I don’t see the use case for your second suggestion. Can you elaborate on situations where you think it’d make sense to have variable column gaps?

**Comment by thellmund** [comment]
Closed due to inactivity.
