### ISSUE TITLE
onFirstVisibleDayChanged error

### ISSUE THREAD

**Issue by christian160984** [thellmund/Android-Week-View#83]
onFirstVisibleDayChanged is called first time but onFirstVisibleDayChanged is not calling first time to scroll in calendar. Second time is calling again

**Comment by thellmund** [comment]
I don’t understand what you mean. Please provide a clearer description of the issue and an example (logs, [SCCEE](http://sscce.org/), etc).

**Comment by christian160984** [comment]
If today is 07/17, to scroll calendar onFirstVisibleDayChanged is not called first time (07/18). 
To scroll again onFirstVisibleDayChanged is called (07/18) but day 18 is not visible and first day column is 07/19.
The issue is onFirstVisibleDayChanged is not called first time.
You put a log onFirstVisibleDayChanged and you will see the issue

**Comment by thellmund** [comment]
You’re right, it’s still behaving weirdly in version 3.4.2. I’ve made some changes in version 4.0.0 that should make it more precise. I plan to release version 4.0.0 next month.
