### ISSUE TITLE
Auto resize text view in event when its available size 

### ISSUE THREAD

**Issue by kingvhit** [thellmund/Android-Week-View#84]
Hi, I'm back :D 

So, I'm found a new issue when I try to use `app:adaptiveEventTextSize="true"` in my WeekView

When I set it in XML, and then move to date has an event, when I zoom out and then zoom in, the week view is not responding at all.

No use `app:adaptiveEventTextSize="true"`, It's OK
[None_use_adaptive.mp4.zip](https://github.com/thellmund/Android-Week-View/files/3404537/None_use_adaptive.mp4.zip)

Use `app:adaptiveEventTextSize="true"`, It's not responding when zooming out and then zooms in, this app like ANR behavior.
[Use_adaptive.mp4.zip](https://github.com/thellmund/Android-Week-View/files/3404541/Use_adaptive.mp4.zip)

The behavior seems to be like the CompleteActivity on sample project when we seek the value of SeekBar.

Do you know any suggestions?

**Comment by thellmund** [comment]
Thanks for reporting. I’ll have a look.

**Comment by thellmund** [comment]
I made some tweaks in 1495d22f4da863e1b1033fbd83c2762ded97e5fb. Can you let me know if your issues persist?
