### ISSUE TITLE
move event by drag and drop

### ISSUE THREAD

**Issue by tdc-w** [thellmund/Android-Week-View#85]
I'm thinking of a specification that moves event by drag and drop like RecyclerView
I don't really understand the specifications of WeekView, but is it possible to do this in future updates?
Thanks.

**Comment by thellmund** [comment]
I don’t intend on adding drag-&-drop to the library. When you long press on an event, you can already get its coordinates, so you could probably build your own drag-&-drop mechanism on top of WeekView.
