### ISSUE TITLE
Provide migration guide from v3 to v4

### ISSUE THREAD

**Issue by thellmund** [thellmund/Android-Week-View#86]

**Comment by kingvhit** [comment]
Sorry for touching you but could you tell us do you have any fixed plan for this migration?
I'm looking some comment that you have plan to release in the mid of Aug.
Thank you very much for your best library.

**Comment by thellmund** [comment]
I initially planned to release the new version by mid-August, but some issues came up so that I wasn‘t able to go through with it. I hope to be able to get it done within the next week.
