### ISSUE TITLE
Event does not occupy all width

### ISSUE THREAD

**Issue by christian160984** [thellmund/Android-Week-View#89]
![Screenshot_20190719](https://user-images.githubusercontent.com/7393899/61529555-eab6c500-aa21-11e9-85c6-412136253f02.jpg)

The events 1, 2 and 3 are loaded on start. They have this parameters:
ev1 -> "start": 1563534000000, "end": 1563535800000
ev2 -> "start": 1563534000000, "end": 1563535800000
ev3 -> "start": 1563534000000, "end": 1563544800000

When I create another event below, it does not occupy all width. He should stick to the ev3. Ev5 pararmeters:

5 -> "start": 1563535860000, "end": 1563537600000

**Comment by thellmund** [comment]
Thanks for reporting, @christian160984! I committed 515270ca7c771ed65105d0e40a36b1706f989c3f, which addresses this issue. Let me know if there are edge cases where it doesn’t work or if you experience any other issues.
