### ISSUE TITLE
EmptyViewLongPress called on EventLongPress

### ISSUE THREAD

**Issue by lakhwinderdebut** [thellmund/Android-Week-View#92]
**Description**
I set long-press listeners on week view

        weekView?.emptyViewLongPressListener = this
        weekView?.setEventLongPressListener(this)

But when I long  press on event, both eventLongPress & emptyViewLongPress gets called

**To Reproduce**
1. Set an event at some time after the current time.
2. Long press on an empty view(No Event Set), emptyViewLongPressListener gets called
3. Now long-press on an event, emptyViewLongPressListener also gets called along with 
eventLongPressListener

**Expected behavior**
A respected listener must be called only,
eventLongPress: eventLongPressListener
emptyViewLongPress: emptyViewLongPressListener

**Additional context**
 - Android version: [e.g. Android 9.0]
 - WeekView version: [e.g. 3.4.2]

**Comment by thellmund** [comment]
Thanks for reporting, @lakhwinderdebut! I was missing a simple `return` 🤦‍♂
Fixed it in 5aed30c03f9e7474ec2e60b8971ac0da88f02ce7 and will release it as part of version 4.0.

**Comment by lakhwinderdebut** [comment]
Thanks, @thellmund , I really appreciate the response time.
Thanks for this lovely library

**Comment by thellmund** [comment]
Probably around mid-August.
