### ISSUE TITLE
set the number of days

### ISSUE THREAD

**Issue by HQLIE2018** [thellmund/Android-Week-View#93]
How to set the number of days displayed in the head instead of looping

**Comment by thellmund** [comment]
What do you mean by “looping”?

**Comment by HQLIE2018** [comment]
For example, I want to set the display for 15 days in the head, not all

**Comment by thellmund** [comment]
You can use `weekView.setMinDate(Calendar)` and `weekView.setMaxDate(Calendar)`. Be sure to check out the [wiki](https://github.com/thellmund/Android-Week-View/wiki/Public-Methods), which describes all available methods.
